# Generated by Django 5.2.8 on 2026-07-20 19:15

import django.db.models.deletion
import django.utils.timezone
import mensajeria.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('DIRECT', 'Directa 1-a-1'), ('GROUP', 'Grupo')], default='DIRECT', max_length=10)),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('ultimo_mensaje_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ultimo_mensaje_en'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('editado_en', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('es_sistema', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mensajeria.conversation')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=mensajeria.models.attachment_upload_to)),
                ('nombre_original', models.CharField(max_length=255)),
                ('mime', models.CharField(blank=True, max_length=120)),
                ('tamano', models.PositiveBigIntegerField(default=0)),
                ('es_imagen', models.BooleanField(default=False)),
                ('ancho', models.PositiveIntegerField(blank=True, null=True)),
                ('alto', models.PositiveIntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='mensajeria.message')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REUNION', 'Reunión / Videollamada'), ('TAREA', 'Tarea')], default='REUNION', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('todo_el_dia', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='mensajeria.conversation')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario_creados', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='eventos_calendario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inicio'],
                'indexes': [models.Index(fields=['inicio'], name='mensajeria__inicio_25dd4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrabacionVideollamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=300)),
                ('egress_id', models.CharField(blank=True, max_length=80)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('detenida_en', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grabaciones', to='mensajeria.conversation')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_grabaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['conversation', 'creado'], name='mensajeria__convers_8189d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvitacionVideollamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('revocado', models.BooleanField(default=False)),
                ('usos', models.PositiveIntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_video', to='mensajeria.conversation')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_invitaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['conversation', 'revocado'], name='mensajeria__convers_6de79f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_admin', models.BooleanField(default=False)),
                ('silenciado', models.BooleanField(default=False)),
                ('unido_en', models.DateTimeField(auto_now_add=True)),
                ('salido_en', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='mensajeria.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_membresias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'salido_en'], name='mensajeria__user_id_e0abb7_idx')],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'user'), name='chat_membership_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'creado'], name='mensajeria__convers_c8dcc2_idx'),
        ),
    ]
