# Generated by Django 5.2.8 on 2026-07-20 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='es_recordatorios',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RecordatorioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIA_ANTES', 'Un día antes'), ('DIA', 'El mismo día')], max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='mensajeria.eventocalendario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_evento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evento', 'user', 'tipo'), name='recordatorio_evento_uniq')],
            },
        ),
    ]
