# Generated by Django 5.2.8 on 2026-07-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_conversation_es_recordatorios_recordatorioevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendario',
            name='canal_recordatorio',
            field=models.CharField(choices=[('CHAT', 'Solo chat'), ('CORREO', 'Correo'), ('WHATSAPP', 'WhatsApp')], default='CHAT', max_length=10),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='recordatorio_destino',
            field=models.CharField(blank=True, help_text='Correo o teléfono (WhatsApp) según el canal', max_length=120),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='recordatorio_ext_dia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='recordatorio_ext_dia_antes',
            field=models.BooleanField(default=False),
        ),
    ]
