# Generated by Django 5.2.8 on 2026-03-03 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Tótem Principal', max_length=100)),
                ('capacidad_total', models.DecimalField(decimal_places=2, help_text='Capacidad máxima en litros', max_digits=10)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, help_text='Litros disponibles actualmente', max_digits=10)),
                ('porcentaje_alerta', models.DecimalField(decimal_places=2, default=15.0, help_text='Porcentaje para enviar alerta de bajo nivel', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_economico', models.CharField(max_length=50, unique=True, verbose_name='Número de Unidad')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CargaDiesel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('odometro', models.DecimalField(decimal_places=2, max_digits=12)),
                ('litros_diesel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('litros_thermo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('litros_urea', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('foto_bomba', models.ImageField(upload_to='cargas/bombas/')),
                ('foto_odometro', models.ImageField(upload_to='cargas/odometros/')),
                ('rendimiento', models.DecimalField(blank=True, decimal_places=2, help_text='Km/L calculado automáticamente', max_digits=8, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Despachador')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargas_diesel.unidad')),
            ],
        ),
    ]
