# Generated by Django 5.2.8 on 2026-03-03 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas_diesel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorDiesel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Proveedor')),
                ('activo', models.BooleanField(default=True, help_text='Si es False, fue editado/eliminado y solo sirve para historial')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cargadiesel',
            options={'permissions': [('admin_diesel', 'Puede ver el dashboard y administrar el tótem'), ('relleno_diesel', 'Puede acceder al formulario y registrar cargas')]},
        ),
        migrations.AddField(
            model_name='totem',
            name='cantidad_urea',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Urea disponible', max_digits=10),
        ),
        migrations.AddField(
            model_name='totem',
            name='capacidad_urea',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Capacidad máxima Urea', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cargadiesel',
            name='rendimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='totem',
            name='cantidad_actual',
            field=models.DecimalField(decimal_places=2, help_text='Diésel disponible', max_digits=10),
        ),
        migrations.AlterField(
            model_name='totem',
            name='capacidad_total',
            field=models.DecimalField(decimal_places=2, help_text='Capacidad máxima Diésel', max_digits=10),
        ),
        migrations.AlterField(
            model_name='totem',
            name='porcentaje_alerta',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_combustible', models.CharField(choices=[('diesel', 'Diésel'), ('urea', 'Urea')], default='diesel', max_length=10)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada (+)'), ('salida', 'Salida (-)')], max_length=10)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompraCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diesel', 'Diésel'), ('urea', 'Urea')], default='diesel', max_length=10)),
                ('proveedor_historico', models.CharField(help_text='Congela el nombre del proveedor en la fecha de compra', max_length=150)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.FileField(blank=True, null=True, upload_to='cargas/facturas/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargas_diesel.proveedordiesel')),
            ],
        ),
    ]
