# Generated by Django 5.2.8 on 2026-03-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas_diesel', '0002_proveedordiesel_alter_cargadiesel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totem',
            name='porcentaje_alerta',
        ),
        migrations.AddField(
            model_name='totem',
            name='alerta_litros_diesel',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Alerta por correo si baja de estos litros', max_digits=10),
        ),
        migrations.AddField(
            model_name='totem',
            name='alerta_litros_urea',
            field=models.DecimalField(decimal_places=2, default=200, help_text='Alerta por correo si baja de estos litros', max_digits=10),
        ),
        migrations.AlterField(
            model_name='totem',
            name='cantidad_actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Diésel disponible', max_digits=10),
        ),
        migrations.AlterField(
            model_name='totem',
            name='capacidad_total',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Capacidad máxima Diésel', max_digits=10),
        ),
    ]
