# Generated by Django 5.2.8 on 2026-04-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas_diesel', '0003_remove_totem_porcentaje_alerta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargadiesel',
            options={},
        ),
        migrations.AlterField(
            model_name='compracombustible',
            name='proveedor_historico',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='proveedordiesel',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='totem',
            name='alerta_litros_diesel',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totem',
            name='alerta_litros_urea',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totem',
            name='cantidad_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totem',
            name='cantidad_urea',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totem',
            name='capacidad_total',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totem',
            name='capacidad_urea',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
