# Generated by Django 5.2.8 on 2026-04-02 04:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

def create_default_patio(apps, schema_editor):
    Patio = apps.get_model('cargas_diesel', 'Patio')
    # Creamos un patio temporal con ID 1 para que los registros que ya tenías tengan a dónde apuntar
    Patio.objects.get_or_create(
        id=1,
        defaults={
            'nombre': 'Patio Principal',
            'codigo': 'DEF-1',
            'direccion': 'Generado automáticamente por migración',
            'activo': True
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cargas_diesel', '0004_alter_cargadiesel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Patio')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código (ej: MTY, CHI)')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patio / Sucursal',
                'verbose_name_plural': 'Patios / Sucursales',
                'ordering': ['nombre'],
            },
        ),
        
        # Ejecutamos nuestra función para inyectar el Patio ID 1
        migrations.RunPython(create_default_patio),

        migrations.AlterModelOptions(
            name='ajusteinventario',
            options={'ordering': ['-fecha'], 'verbose_name': 'Ajuste de Inventario', 'verbose_name_plural': 'Ajustes de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='cargadiesel',
            options={'ordering': ['-fecha_carga'], 'verbose_name': 'Carga de Diésel', 'verbose_name_plural': 'Cargas de Diésel'},
        ),
        migrations.AlterModelOptions(
            name='compracombustible',
            options={'ordering': ['-fecha'], 'verbose_name': 'Compra de Combustible', 'verbose_name_plural': 'Compras de Combustible'},
        ),
        migrations.AlterModelOptions(
            name='proveedordiesel',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor de Combustible', 'verbose_name_plural': 'Proveedores de Combustible'},
        ),
        migrations.AlterModelOptions(
            name='totem',
            options={'verbose_name': 'Tótem de Combustible', 'verbose_name_plural': 'Tótems de Combustible'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['numero_economico'], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.RemoveField(
            model_name='compracombustible',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='compracombustible',
            name='proveedor_historico',
        ),
        migrations.RemoveField(
            model_name='totem',
            name='alerta_litros_diesel',
        ),
        migrations.RemoveField(
            model_name='totem',
            name='alerta_litros_urea',
        ),
        migrations.RemoveField(
            model_name='totem',
            name='cantidad_actual',
        ),
        migrations.RemoveField(
            model_name='totem',
            name='capacidad_total',
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='cantidad_anterior',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='cantidad_posterior',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='cargadiesel',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='cargadiesel',
            name='hrs_thermo',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Horas Thermo'),
        ),
        migrations.AddField(
            model_name='cargadiesel',
            name='precio_litro',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='compracombustible',
            name='factura_pdf',
            field=models.FileField(blank=True, null=True, upload_to='diesel/facturas/%Y/%m/', verbose_name='Factura PDF'),
        ),
        migrations.AddField(
            model_name='compracombustible',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='compracombustible',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de Factura'),
        ),
        migrations.AddField(
            model_name='compracombustible',
            name='proveedor_nombre',
            field=models.CharField(default='Desconocido', editable=False, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedordiesel',
            name='contacto',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='proveedordiesel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedordiesel',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='proveedordiesel',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='totem',
            name='alerta_diesel',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='Alerta Diésel (L)'),
        ),
        migrations.AddField(
            model_name='totem',
            name='alerta_urea',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10, verbose_name='Alerta Urea (L)'),
        ),
        migrations.AddField(
            model_name='totem',
            name='cantidad_diesel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Diésel Disponible (L)'),
        ),
        migrations.AddField(
            model_name='totem',
            name='capacidad_diesel',
            field=models.DecimalField(decimal_places=2, default=14000, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Capacidad Total Diésel (L)'),
        ),
        migrations.AddField(
            model_name='totem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de Unidad'),
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='litros',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='motivo',
            field=models.CharField(max_length=255, verbose_name='Motivo del Ajuste'),
        ),
        migrations.AlterField(
            model_name='cargadiesel',
            name='foto_bomba',
            field=models.ImageField(upload_to='diesel/bombas/%Y/%m/', verbose_name='Foto Bomba'),
        ),
        migrations.AlterField(
            model_name='cargadiesel',
            name='foto_odometro',
            field=models.ImageField(upload_to='diesel/odometros/%Y/%m/', verbose_name='Foto Odómetro'),
        ),
        migrations.AlterField(
            model_name='cargadiesel',
            name='litros_diesel',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cargadiesel',
            name='odometro',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Odómetro (km)'),
        ),
        migrations.AlterField(
            model_name='cargadiesel',
            name='rendimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Rendimiento Km/L'),
        ),
        migrations.AlterField(
            model_name='cargadiesel',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='cargas_diesel.unidad'),
        ),
        migrations.AlterField(
            model_name='compracombustible',
            name='litros',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='compracombustible',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='compracombustible',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='cargas_diesel.proveedordiesel'),
        ),
        migrations.AlterField(
            model_name='compracombustible',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='totem',
            name='cantidad_urea',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Urea Disponible (L)'),
        ),
        migrations.AlterField(
            model_name='totem',
            name='capacidad_urea',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Capacidad Total Urea (L)'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción / Alias'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='numero_economico',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número Económico'),
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='patio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='cargas_diesel.patio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargadiesel',
            name='patio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='cargas_diesel.patio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compracombustible',
            name='patio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='cargas_diesel.patio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totem',
            name='patio',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='totem', to='cargas_diesel.patio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='patio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='cargas_diesel.patio'),
        ),
        migrations.CreateModel(
            name='PerfilUsuarioDiesel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_global', models.BooleanField(default=False, verbose_name='Acceso Global (ve todos los patios)')),
                ('patios', models.ManyToManyField(blank=True, related_name='usuarios', to='cargas_diesel.patio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_diesel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]