# Generated by Django 5.2.7 on 2026-01-30 21:35

import RH.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RH", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="origen_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID original del sistema de origen (importaciones/backups)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="acta_nacimiento_documento",
            field=models.FileField(
                blank=True, null=True, upload_to=RH.models.empleado_acta_nacimiento_path
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="aviso_retencion_infonavit_documento",
            field=models.FileField(
                blank=True, null=True, upload_to=RH.models.empleado_aviso_infonavit_path
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="carta_recomendacion_1_documento",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=RH.models.empleado_carta_recomendacion_1_path,
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="carta_recomendacion_2_documento",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=RH.models.empleado_carta_recomendacion_2_path,
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="clabe_interbancaria",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="comprobante_domicilio",
            field=models.FileField(
                blank=True, null=True, upload_to=RH.models.empleado_domicilio_path
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="comprobante_estudios_documento",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=RH.models.empleado_comprobante_estudios_path,
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="constancia_fiscal_documento",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=RH.models.empleado_constancia_fiscal_path,
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="curp",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Formato de CURP inválido.",
                        regex="^[A-Z]{4}[0-9]{6}[H,M][A-Z]{2}[B-DF-HJ-NP-TV-Z]{3}[0-9A-Z]{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="curriculum_vitae",
            field=models.FileField(
                blank=True, null=True, upload_to=RH.models.empleado_cv_path
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="direccion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="division_operativa",
            field=models.ManyToManyField(blank=True, to="RH.divisionoperativa"),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="empresa",
            field=models.CharField(
                blank=True,
                choices=[("MIGMAR", "Migmar"), ("MARCO_MORALES", "Marco Morales")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="ine_documento",
            field=models.FileField(
                blank=True, null=True, upload_to=RH.models.empleado_ine_path
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="nombre_conyuge",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="nss",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="NSS debe ser un número de 11 dígitos.",
                        regex="^\\d{11}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="numero_tarjeta",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="rfc",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Formato de RFC inválido.",
                        regex="^[A-Z&Ñ]{3,4}[0-9]{6}[A-Z0-9]{3}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="semanas_cotizadas_imss_documento",
            field=models.FileField(
                blank=True, null=True, upload_to=RH.models.empleado_semanas_imss_path
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="telefono_conyuge",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="telefono_personal",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número de teléfono debe estar en el formato: '+999999999'. Hasta 15 dígitos permitidos.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="tipo_carga",
            field=models.ManyToManyField(blank=True, to="RH.tipocarga"),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="tipo_viaje",
            field=models.ManyToManyField(blank=True, to="RH.tipoviaje"),
        ),
    ]
