# Generated by Django 5.2.7 on 2026-01-31 15:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RH", "0002_empleado_origen_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="fecha_contratacion",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="numero_empleado",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
