# Generated by Django 5.2.7 on 2026-02-05 17:31

import django.utils.timezone
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0003_alter_empleado_fecha_contratacion_alter_empleado_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='puesto_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]