# Generated by Django 5.2.7 on 2026-02-25 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RH", "0004_empleado_fecha_ingreso_empleado_puesto_anterior"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="fecha_contratacion",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="fecha_ingreso",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
