# Generated by Django 5.2.7 on 2026-02-25 12:00

import django.utils.timezone
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0005_alter_empleado_fecha_contratacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
