# Generated by Django 5.2.7 on 2026-02-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RH", "0007_reset_sequences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="empresa",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MIGMAR", "Migmar"),
                    ("MARCO_MORALES", "Marco Morales"),
                    ("CHIHUAHUA", "Chihuahua"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ControlVacante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa",
                    models.CharField(
                        choices=[
                            ("MIGMAR", "Migmar"),
                            ("MARCO_MORALES", "Marco Morales"),
                            ("CHIHUAHUA", "Chihuahua"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cantidad_presupuestada",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad Objetivo"
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="RH.divisionoperativa",
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles_vacantes",
                        to="RH.puesto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control de Vacante",
                "verbose_name_plural": "Control de Vacantes",
                "unique_together": {("empresa", "puesto", "division")},
            },
        ),
    ]
