# Generated by Django 5.2.7 on 2026-03-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RH", "0008_alter_empleado_empresa_controlvacante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacacion",
            name="tipo_vacacion",
            field=models.CharField(
                choices=[
                    ("ORDINARIAS", "Vacaciones Ordinarias"),
                    ("ANTICIPADAS", "Vacaciones Anticipadas"),
                    ("PRORROGA", "Prórroga"),
                    ("EXTRA", "Vacaciones Extra"),
                    ("HISTORICO", "Registro Histórico"),
                ],
                default="ORDINARIAS",
                max_length=20,
            ),
        ),
    ]
