# Generated by Django 5.2.8 on 2026-07-20 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0014_empleado_empresas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('contenido', models.TextField(blank=True, help_text='HTML con marcadores {{variable}}')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_contrato_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de contrato',
                'verbose_name_plural': 'Plantillas de contrato',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContratoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido_html', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_generados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_generados', to='RH.empleado')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_generados', to='RH.plantillacontrato')),
            ],
            options={
                'verbose_name': 'Contrato generado',
                'verbose_name_plural': 'Contratos generados',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['empleado', '-creado'], name='RH_contrato_emplead_695823_idx')],
            },
        ),
    ]
