# Generated by Django 5.2.8 on 2026-07-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0015_plantillacontrato_contratogenerado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellido', 'nombre'], 'permissions': [('acceso_rh', 'Acceso al módulo de Recursos Humanos'), ('exportar_rh', 'Exportar nómina / reportes de RH')], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
