# Generated by Django 5.2.8 on 2026-04-22 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nombre', models.CharField(default='3R Recycling', max_length=200, verbose_name='Nombre de la empresa')),
                ('empresa_rfc', models.CharField(blank=True, default='', max_length=13, verbose_name='RFC de la empresa')),
                ('empresa_logo_url', models.URLField(blank=True, default='', verbose_name='URL del logotipo')),
                ('empresa_slogan', models.CharField(blank=True, default='', max_length=300, verbose_name='Slogan')),
                ('empresa_direccion', models.TextField(blank=True, default='', verbose_name='Dirección física')),
                ('empresa_telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono principal')),
                ('empresa_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email principal')),
                ('empresa_sitio_web', models.URLField(blank=True, default='', verbose_name='Sitio web')),
                ('color_primario', models.CharField(default='#1a73e8', help_text='Hex CSS: #RRGGBB', max_length=7, verbose_name='Color primario')),
                ('color_secundario', models.CharField(default='#34a853', help_text='Hex CSS: #RRGGBB', max_length=7, verbose_name='Color secundario')),
                ('color_acento', models.CharField(default='#fbbc05', max_length=7, verbose_name='Color de acento')),
                ('color_peligro', models.CharField(default='#ea4335', max_length=7, verbose_name='Color de peligro / error')),
                ('fuente_principal', models.CharField(default='Inter, sans-serif', max_length=100, verbose_name='Fuente principal')),
                ('tema_oscuro_por_defecto', models.BooleanField(default=False, verbose_name='Tema oscuro por defecto')),
                ('idioma_por_defecto', models.CharField(default='es', max_length=10, verbose_name='Idioma por defecto (es/en)')),
                ('zona_horaria', models.CharField(default='America/Monterrey', max_length=50, verbose_name='Zona horaria')),
                ('moneda_por_defecto', models.CharField(default='MXN', max_length=3, verbose_name='Moneda por defecto (MXN/USD)')),
                ('modulo_remisiones', models.BooleanField(default=True, verbose_name='Módulo Remisiones')),
                ('modulo_plastico', models.BooleanField(default=True, verbose_name='Módulo Plástico')),
                ('modulo_tarimas', models.BooleanField(default=True, verbose_name='Módulo Control Tarimas')),
                ('modulo_maquila', models.BooleanField(default=True, verbose_name='Módulo Maquila')),
                ('modulo_trane', models.BooleanField(default=True, verbose_name='Módulo TRANE')),
                ('modulo_medline', models.BooleanField(default=True, verbose_name='Módulo Medline')),
                ('modulo_rh', models.BooleanField(default=True, verbose_name='Módulo RH')),
                ('modulo_bancos', models.BooleanField(default=True, verbose_name='Módulo Bancos')),
                ('modulo_compras', models.BooleanField(default=True, verbose_name='Módulo Compras')),
                ('modulo_cxp', models.BooleanField(default=True, verbose_name='Módulo CxP')),
                ('modulo_facturacion', models.BooleanField(default=True, verbose_name='Módulo Facturación')),
                ('modulo_diesel', models.BooleanField(default=True, verbose_name='Módulo Diesel')),
                ('modulo_chat', models.BooleanField(default=True, verbose_name='Módulo Chat')),
                ('modulo_ia', models.BooleanField(default=False, verbose_name='Módulo IA')),
                ('modulo_dashboard_patio', models.BooleanField(default=True, verbose_name='Dashboard Patio')),
                ('modulo_reportes_kpi', models.BooleanField(default=True, verbose_name='Reportes y KPIs')),
                ('merma_umbral_alerta_default', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='% Merma umbral de alerta (default)')),
                ('peso_default_unidad_medida', models.CharField(choices=[('TON', 'Toneladas'), ('KG', 'Kilogramos')], default='TON', max_length=3, verbose_name='Unidad de peso por defecto')),
                ('dias_auditoria_limite', models.PositiveIntegerField(default=30, verbose_name='Días límite para auditar remisión')),
                ('permitir_remision_sin_boleta', models.BooleanField(default=True, verbose_name='Permitir remisión sin boleta de báscula')),
                ('auto_cancelar_remision_dias', models.PositiveIntegerField(default=0, help_text='0 = nunca cancelar automáticamente', verbose_name='Días para auto-cancelar remisión inactiva')),
                ('folio_medline_formato', models.CharField(default='3R-{YYYY}-{MM}-{NNN}', max_length=20, verbose_name='Formato folio Medline')),
                ('rh_dias_vacaciones_primer_anio', models.PositiveIntegerField(default=12, verbose_name='Días vacaciones 1er año')),
                ('rh_dias_vacaciones_incremento', models.PositiveIntegerField(default=2, verbose_name='Días extras por año adicional')),
                ('rh_prestamo_limite_meses_sueldo', models.PositiveIntegerField(default=3, verbose_name='Límite préstamo (# sueldos mensuales)')),
                ('rh_prestamo_max_porcentaje_descuento', models.DecimalField(decimal_places=2, default=40.0, max_digits=5, verbose_name='% máximo de descuento semanal para préstamos')),
                ('rh_empresa_choices', models.JSONField(blank=True, default=list, help_text='Lista de empresas para el módulo RH. Ej: ["MIGMAR","MARCO_MORALES"]', verbose_name='Empresas RH disponibles')),
                ('diesel_alerta_minima_litros', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Litros mínimos antes de alerta diesel')),
                ('urea_alerta_minima_litros', models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='Litros mínimos antes de alerta urea')),
                ('compras_aprobacion_requerida', models.BooleanField(default=True, verbose_name='Solicitudes de compra requieren aprobación')),
                ('compras_monto_aprobacion_automatica', models.DecimalField(decimal_places=2, default=0, help_text='Montos menores a este valor se aprueban automáticamente. 0 = desactivado', max_digits=12, verbose_name='Monto auto-aprobación compras')),
                ('cxp_dias_alerta_vencimiento', models.PositiveIntegerField(default=7, verbose_name='Días antes del vencimiento para alertar CxP')),
                ('bancos_tc_default', models.DecimalField(decimal_places=4, default=17.0, max_digits=10, verbose_name='Tipo de cambio USD/MXN por defecto')),
                ('notificaciones_email_activas', models.BooleanField(default=True, verbose_name='Notificaciones por email activas')),
                ('notificaciones_whatsapp_activas', models.BooleanField(default=False, verbose_name='Notificaciones WhatsApp activas')),
                ('email_alertas_merma', models.TextField(blank=True, default='', help_text='Emails separados por coma para alertas de merma', verbose_name='Emails alertas merma')),
                ('email_alertas_cxp', models.TextField(blank=True, default='', help_text='Emails separados por coma para alertas CxP', verbose_name='Emails alertas CxP')),
                ('fiscalapi_key', models.CharField(blank=True, default='', max_length=200, verbose_name='FiscalAPI Key (timbrado CFDI)')),
                ('fiscalapi_url', models.URLField(blank=True, default='https://test.fiscalapi.com/api/v4', verbose_name='FiscalAPI URL')),
                ('fiscalapi_modo_produccion', models.BooleanField(default=False, verbose_name='FiscalAPI en producción')),
                ('banxico_api_token', models.CharField(blank=True, default='', max_length=200, verbose_name='Banxico API Token (tipo de cambio)')),
                ('twilio_activo', models.BooleanField(default=False, verbose_name='Twilio WhatsApp activo')),
                ('twilio_whatsapp_from', models.CharField(blank=True, default='', max_length=50, verbose_name='Número WhatsApp emisor Twilio')),
                ('items_por_pagina', models.PositiveIntegerField(default=25, verbose_name='Items por página (API y listas)')),
                ('items_por_pagina_maximo', models.PositiveIntegerField(default=200, verbose_name='Máximo items por página permitido')),
                ('storage_backend', models.CharField(choices=[('s3', 'AWS S3'), ('local', 'Sistema de archivos local')], default='s3', max_length=20, verbose_name='Backend de almacenamiento')),
                ('s3_bucket_nombre', models.CharField(blank=True, default='3rrecycling', max_length=100, verbose_name='Nombre del bucket S3')),
                ('s3_region', models.CharField(blank=True, default='', max_length=50, verbose_name='Región S3')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Último usuario que modificó la configuración')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
                'permissions': [('can_edit_config', 'Puede editar la configuración del sistema')],
            },
        ),
    ]
