# Generated by Django 5.2.8 on 2026-07-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='ia_api_key',
            field=models.CharField(blank=True, default='', help_text='API key del proveedor (Anthropic o DeepSeek)', max_length=255, verbose_name='API Key de IA (texto)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='ia_base_url',
            field=models.URLField(blank=True, default='', help_text='Vacío = default. DeepSeek: https://api.deepseek.com', verbose_name='URL base del proveedor de IA'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='ia_modelo',
            field=models.CharField(blank=True, default='', help_text='Vacío = el por defecto del proveedor', max_length=60, verbose_name='Modelo de IA'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='ia_proveedor',
            field=models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('deepseek', 'DeepSeek')], default='anthropic', help_text='Proveedor de IA para asistentes e informes', max_length=20, verbose_name='Proveedor de IA'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='imagen_api_key',
            field=models.CharField(blank=True, default='', help_text='Para generar imágenes en Canvas (aistudio.google.com/apikey)', max_length=255, verbose_name='API Key de Google Gemini (imágenes)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='imagen_modelo',
            field=models.CharField(blank=True, default='', help_text='Vacío = el por defecto', max_length=80, verbose_name='Modelo de imagen de Gemini'),
        ),
    ]
