# Generated by Django 5.1.7 on 2025-11-08 02:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_seen",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
