# Generated by Django 5.1.7 on 2025-12-08 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ternium', '0012_alter_remision_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosFiscales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('razon_social', models.CharField(help_text='Tal cual aparece en la constancia', max_length=255)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('cliente_interno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_fiscales', to='ternium.cliente')),
                ('empresa_interna', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_fiscales', to='ternium.empresa')),
                ('regimen_fiscal', models.ForeignKey(limit_choices_to={'tipo': 'RegimenFiscal'}, on_delete=django.db.models.deletion.PROTECT, to='facturacion.catalogosat')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(default='A', max_length=10)),
                ('folio', models.CharField(max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('tipo_comprobante', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso (Nota de Crédito)'), ('P', 'Pago (Complemento)')], default='I', max_length=1)),
                ('metodo_pago', models.CharField(choices=[('PUE', 'Pago en una sola exhibición'), ('PPD', 'Pago en parcialidades o diferido')], default='PUE', max_length=3)),
                ('forma_pago', models.CharField(choices=[('01', 'Efectivo'), ('03', 'Transferencia'), ('99', 'Por definir')], default='03', max_length=2)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuestos_trasladados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos_retenidos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='Folio Fiscal (UUID)')),
                ('xml_timbrado', models.FileField(blank=True, null=True, upload_to='facturas/xml/')),
                ('pdf_representacion', models.FileField(blank=True, null=True, upload_to='facturas/pdf/')),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente de Timbrar'), ('TIMBRADO', 'Timbrado Exitosamente'), ('CANCELADO', 'Cancelado'), ('ERROR', 'Error al Timbrar')], default='PENDIENTE', max_length=15)),
                ('tipo_relacion', models.CharField(blank=True, help_text='04 para Sustitución, 07 para Anticipos...', max_length=2, null=True)),
                ('cfdi_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.factura', verbose_name='CFDI Relacionado')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_emitidas', to='facturacion.datosfiscales')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_recibidas', to='facturacion.datosfiscales')),
                ('remisiones', models.ManyToManyField(blank=True, related_name='facturas', to='ternium.remision')),
                ('uso_cfdi', models.ForeignKey(limit_choices_to={'tipo': 'UsoCFDI'}, on_delete=django.db.models.deletion.PROTECT, to='facturacion.catalogosat')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_prod_serv', models.CharField(help_text='Clave SAT Prod/Serv', max_length=15)),
                ('clave_unidad', models.CharField(help_text='Clave SAT Unidad', max_length=5)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unidad', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('objeto_impuesto', models.CharField(default='02', max_length=2)),
                ('iva_tasa', models.DecimalField(decimal_places=4, default=0.16, max_digits=6)),
                ('iva_importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva_ret_tasa', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('iva_ret_importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='facturacion.factura')),
            ],
        ),
        migrations.CreateModel(
            name='ComplementoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('num_operacion', models.CharField(blank=True, help_text='Referencia bancaria', max_length=50)),
                ('uuid_pago', models.CharField(blank=True, max_length=36, null=True)),
                ('xml_pago', models.FileField(blank=True, upload_to='pagos/xml/')),
                ('pdf_pago', models.FileField(blank=True, upload_to='pagos/pdf/')),
                ('estatus', models.CharField(default='PENDIENTE', max_length=15)),
                ('forma_pago', models.ForeignKey(limit_choices_to={'tipo': 'FormaPago'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='facturacion.catalogosat')),
                ('factura_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='facturacion.factura')),
            ],
        ),
    ]
