# Generated by Django 5.1.7 on 2025-12-08 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('ternium', '0016_remove_lugar_direccion_fiscal_lugar_calle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosfiscales',
            name='empresa_interna',
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='es_emisor',
            field=models.BooleanField(default=False, help_text='Marcar verdadero si estos son TUS datos'),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='cliente_interno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.cliente'),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='codigo_postal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='razon_social',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='regimen_fiscal',
            field=models.CharField(choices=[('601', '601 - General de Ley Personas Morales'), ('612', '612 - Personas Físicas con Actividades Empresariales'), ('626', '626 - Régimen Simplificado de Confianza')], max_length=5),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='rfc',
            field=models.CharField(max_length=13),
        ),
    ]
