# Generated by Django 5.1.7 on 2025-12-08 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_remove_datosfiscales_empresa_interna_and_more'),
        ('ternium', '0016_remove_lugar_direccion_fiscal_lugar_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfiscales',
            name='cliente_interno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_fiscales', to='ternium.cliente'),
        ),
    ]
