# Generated by Django 5.1.7 on 2025-12-09 01:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_datosfiscales_cliente_interno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        # ==============================
        # ALTER FIELD → SOLO ESTADO
        # ==============================
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='complementopago',
                    name='forma_pago',
                    field=models.CharField(default='03', max_length=5, verbose_name='Forma de Pago SAT'),
                ),
                migrations.AlterField(
                    model_name='factura',
                    name='uso_cfdi',
                    field=models.CharField(default='G03', max_length=5),
                ),
                migrations.AlterField(
                    model_name='factura',
                    name='forma_pago',
                    field=models.CharField(default='99', max_length=5),
                ),
                migrations.AlterField(
                    model_name='factura',
                    name='metodo_pago',
                    field=models.CharField(default='PPD', max_length=5),
                ),
                migrations.AlterField(
                    model_name='factura',
                    name='moneda',
                    field=models.CharField(default='MXN', max_length=5),
                ),
            ],
        ),

        # ==============================
        # OPCIONES DE MODELO
        # ==============================
        migrations.AlterModelOptions(
            name='complementopago',
            options={'verbose_name': 'Complemento de Pago', 'verbose_name_plural': 'Complementos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='datosfiscales',
            options={'verbose_name': 'Datos Fiscales', 'verbose_name_plural': 'Datos Fiscales'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),

        # ==============================
        # REMOVE FIELD
        # ==============================
        migrations.RemoveField(model_name='complementopago', name='estatus'),
        migrations.RemoveField(model_name='complementopago', name='factura_origen'),
        migrations.RemoveField(model_name='complementopago', name='pdf_pago'),
        migrations.RemoveField(model_name='complementopago', name='xml_pago'),

        migrations.RemoveField(model_name='conceptofactura', name='iva_ret_tasa'),
        migrations.RemoveField(model_name='conceptofactura', name='iva_tasa'),
        migrations.RemoveField(model_name='conceptofactura', name='objeto_impuesto'),

        migrations.RemoveField(model_name='datosfiscales', name='calle'),
        migrations.RemoveField(model_name='datosfiscales', name='colonia'),
        migrations.RemoveField(model_name='datosfiscales', name='estado'),
        migrations.RemoveField(model_name='datosfiscales', name='municipio'),

        migrations.RemoveField(model_name='factura', name='cfdi_relacionado'),
        migrations.RemoveField(model_name='factura', name='estatus'),
        migrations.RemoveField(model_name='factura', name='pdf_representacion'),
        migrations.RemoveField(model_name='factura', name='tipo_comprobante'),
        migrations.RemoveField(model_name='factura', name='tipo_relacion'),
        migrations.RemoveField(model_name='factura', name='total'),
        migrations.RemoveField(model_name='factura', name='uuid'),
        migrations.RemoveField(model_name='factura', name='xml_timbrado'),

        # ==============================
        # ADD FIELD
        # ==============================
        migrations.AddField(
            model_name='complementopago',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pagos/pdf/'),
        ),
        migrations.AddField(
            model_name='complementopago',
            name='archivo_xml',
            field=models.FileField(blank=True, null=True, upload_to='pagos/xml/'),
        ),
        migrations.AddField(
            model_name='complementopago',
            name='factura',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='complementos_pago',
                to='facturacion.factura',
            ),
        ),

        migrations.AddField(
            model_name='datosfiscales',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal'),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='usuario',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='facturacion_datos',
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        # ==============================
        # DELETE MODEL
        # ==============================
        migrations.DeleteModel(
            name='CatalogoSAT',
        ),
    ]
