# Generated by Django 5.1.7 on 2025-12-09 01:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_datosfiscales_cliente_interno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementopago',
            name='forma_pago',
            field=models.CharField(default='03', max_length=5, verbose_name='Forma de Pago SAT'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='uso_cfdi',
            field=models.CharField(default='G03', max_length=5),
        ),
        migrations.AlterModelOptions(
            name='complementopago',
            options={'verbose_name': 'Complemento de Pago', 'verbose_name_plural': 'Complementos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='datosfiscales',
            options={'verbose_name': 'Datos Fiscales', 'verbose_name_plural': 'Datos Fiscales'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.RemoveField(
            model_name='complementopago',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='complementopago',
            name='factura_origen',
        ),
        migrations.RemoveField(
            model_name='complementopago',
            name='pdf_pago',
        ),
        migrations.RemoveField(
            model_name='complementopago',
            name='xml_pago',
        ),
        migrations.RemoveField(
            model_name='conceptofactura',
            name='iva_ret_tasa',
        ),
        migrations.RemoveField(
            model_name='conceptofactura',
            name='iva_tasa',
        ),
        migrations.RemoveField(
            model_name='conceptofactura',
            name='objeto_impuesto',
        ),
        migrations.RemoveField(
            model_name='datosfiscales',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='datosfiscales',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='datosfiscales',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='datosfiscales',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cfdi_relacionado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='pdf_representacion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='tipo_comprobante',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='tipo_relacion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='xml_timbrado',
        ),
        migrations.AddField(
            model_name='complementopago',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pagos/pdf/'),
        ),
        migrations.AddField(
            model_name='complementopago',
            name='archivo_xml',
            field=models.FileField(blank=True, null=True, upload_to='pagos/xml/'),
        ),
        migrations.AddField(
            model_name='complementopago',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complementos_pago', to='facturacion.factura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal'),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para envío de factura'),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='uso_cfdi',
            field=models.CharField(choices=[('G01', 'G01 - Adquisición de mercancías'), ('G03', 'G03 - Gastos en general'), ('I01', 'I01 - Construcciones'), ('P01', 'P01 - Por definir'), ('S01', 'S01 - Sin efectos fiscales'), ('I04', 'I04 - Equipo de computo y accesorios')], default='G03', max_length=5, verbose_name='Uso de CFDI Preferido'),
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturacion_datos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='facturas_emitidas/pdf/', verbose_name='PDF Factura'),
        ),
        migrations.AddField(
            model_name='factura',
            name='archivo_xml',
            field=models.FileField(blank=True, null=True, upload_to='facturas_emitidas/xml/', verbose_name='XML Factura'),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago/Timbrado'), ('pagada', 'Pagada'), ('timbrado', 'Timbrado (Emitida)'), ('cancelada', 'Cancelada'), ('error', 'Error al Timbrar')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='folio_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Folio Fiscal (UUID)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complementopago',
            name='fecha_pago',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complementopago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='complementopago',
            name='num_operacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Operación'),
        ),
        migrations.AlterField(
            model_name='complementopago',
            name='uuid_pago',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UUID del Complemento'),
        ),
        migrations.AlterField(
            model_name='conceptofactura',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='conceptofactura',
            name='clave_prod_serv',
            field=models.CharField(default='01010101', max_length=15),
        ),
        migrations.AlterField(
            model_name='conceptofactura',
            name='clave_unidad',
            field=models.CharField(default='H87', max_length=5),
        ),
        migrations.AlterField(
            model_name='conceptofactura',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='conceptofactura',
            name='iva_importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='conceptofactura',
            name='iva_ret_importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='conceptofactura',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='codigo_postal',
            field=models.CharField(max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='es_emisor',
            field=models.BooleanField(default=False, help_text='Marcar si estos son TUS datos fiscales'),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='razon_social',
            field=models.CharField(max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Régimen Fiscal'),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='rfc',
            field=models.CharField(max_length=13, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='emisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_emitidas', to='facturacion.datosfiscales'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Folio Interno'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(default='99', max_length=5),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(default='PPD', max_length=5),
        ),
        migrations.AlterField(
            model_name='factura',
            name='moneda',
            field=models.CharField(default='MXN', max_length=5),
        ),
        migrations.AlterField(
            model_name='factura',
            name='receptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_recibidas', to='facturacion.datosfiscales'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='serie',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='CatalogoSAT',
        ),
    ]
