# Generated by Django 5.1.7 on 2025-12-10 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_alter_complementopago_forma_pago_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complementopago',
            options={'ordering': ['fecha_pago'], 'verbose_name': 'Complemento de Pago', 'verbose_name_plural': 'Complementos de Pago'},
        ),
        migrations.AddField(
            model_name='complementopago',
            name='moneda',
            field=models.CharField(default='MXN', max_length=10),
        ),
        migrations.AddField(
            model_name='complementopago',
            name='numero_parcialidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Núm. Parcialidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complementopago',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Saldo Anterior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complementopago',
            name='saldo_insoluto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Saldo Insoluto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complementopago',
            name='timbrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complementopago',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='complementopago',
            name='fecha_pago',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='complementopago',
            name='forma_pago',
            field=models.CharField(default='03', max_length=50, verbose_name='Forma de Pago SAT'),
        ),
        migrations.AlterField(
            model_name='datosfiscales',
            name='uso_cfdi',
            field=models.CharField(choices=[('G01', 'G01 - Adquisición de mercancías'), ('G03', 'G03 - Gastos en general'), ('I01', 'I01 - Construcciones'), ('P01', 'P01 - Por definir'), ('S01', 'S01 - Sin efectos fiscales'), ('I04', 'I04 - Equipo de computo y accesorios')], default='G03', max_length=50, verbose_name='Uso de CFDI Preferido'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(default='99', max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(default='PPD', max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='moneda',
            field=models.CharField(default='MXN', max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='uso_cfdi',
            field=models.CharField(default='G03', max_length=50),
        ),
    ]
