# Generated by Django 5.1.7 on 2025-12-14 20:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_alter_complementopago_forma_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ENVOLVEMOS TODO EN SeparateDatabaseAndState.
        # state_operations: Actualiza la lógica interna de Django.
        # database_operations: [] (VACÍO) -> No toca la base de datos (porque ya lo hiciste manualmente).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # 1. Cambios de Opciones y Eliminaciones
                migrations.AlterModelOptions(
                    name='complementopago',
                    options={'verbose_name': 'Complemento de Pago (REP)', 'verbose_name_plural': 'Complementos de Pago (REP)'},
                ),
                migrations.RemoveField(model_name='complementopago', name='factura'),
                migrations.RemoveField(model_name='complementopago', name='monto'),
                migrations.RemoveField(model_name='complementopago', name='uuid_pago'),

                # 2. Nuevos Campos (AddFields)
                migrations.AddField(model_name='complementopago', name='certificado_pago', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='complementopago', name='fecha_timbrado', field=models.DateTimeField(blank=True, null=True)),
                migrations.AddField(model_name='complementopago', name='folio', field=models.PositiveIntegerField(default=1, verbose_name='Folio Interno'), preserve_default=False),
                migrations.AddField(model_name='complementopago', name='moneda', field=models.CharField(default='MXN', max_length=10)),
                migrations.AddField(model_name='complementopago', name='monto_total', field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Monto Total Recibido'), preserve_default=False),
                migrations.AddField(model_name='complementopago', name='no_certificado_sat', field=models.CharField(blank=True, max_length=20, null=True)),
                migrations.AddField(model_name='complementopago', name='receptor', field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='facturacion.datosfiscales', verbose_name='Cliente que paga'), preserve_default=False),
                migrations.AddField(model_name='complementopago', name='sello_pago', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='complementopago', name='sello_sat', field=models.TextField(blank=True, null=True)),
                migrations.AddField(model_name='complementopago', name='serie', field=models.CharField(default='CP', max_length=10)),
                migrations.AddField(model_name='complementopago', name='timbrado', field=models.BooleanField(default=False)),
                migrations.AddField(model_name='complementopago', name='tipo_cadena_pago', field=models.CharField(blank=True, max_length=2, null=True)),
                migrations.AddField(model_name='complementopago', name='tipo_cambio', field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                migrations.AddField(model_name='complementopago', name='usuario', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                migrations.AddField(model_name='complementopago', name='uuid', field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Folio Fiscal (UUID)')),
                migrations.AddField(model_name='complementopago', name='version', field=models.CharField(default='2.0', editable=False, max_length=10)),
                
                # 3. Creación del Modelo Relacionado
                migrations.CreateModel(
                    name='PagoDoctoRelacionado',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('numero_parcialidad', models.PositiveIntegerField()),
                        ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe aplicado')),
                        ('saldo_insoluto', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('moneda_dr', models.CharField(default='MXN', max_length=10)),
                        ('equivalencia_dr', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                        ('complemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_relacionados', to='facturacion.complementopago')),
                        ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to='facturacion.factura')),
                    ],
                ),

                # 4. Modificaciones de Campos (AlterFields - A 50 chars)
                migrations.AlterField(model_name='complementopago', name='fecha_pago', field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                migrations.AlterField(model_name='complementopago', name='forma_pago', field=models.CharField(default='03', max_length=50, verbose_name='Forma de Pago SAT')),
                migrations.AlterField(model_name='datosfiscales', name='uso_cfdi', field=models.CharField(choices=[('G01', 'G01 - Adquisición de mercancías'), ('G03', 'G03 - Gastos en general'), ('I01', 'I01 - Construcciones'), ('P01', 'P01 - Por definir'), ('S01', 'S01 - Sin efectos fiscales'), ('I04', 'I04 - Equipo de computo y accesorios')], default='G03', max_length=50, verbose_name='Uso de CFDI Preferido')),
                migrations.AlterField(model_name='factura', name='forma_pago', field=models.CharField(default='99', max_length=50)),
                migrations.AlterField(model_name='factura', name='metodo_pago', field=models.CharField(default='PPD', max_length=50)),
                migrations.AlterField(model_name='factura', name='moneda', field=models.CharField(default='MXN', max_length=50)),
                migrations.AlterField(model_name='factura', name='uso_cfdi', field=models.CharField(default='G03', max_length=50)),
            ],
            database_operations=[], # <--- ESTO ES LO IMPORTANTE: Lista vacía.
        ),
    ]