# Generated by Django 5.1.7 on 2026-01-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_complementopago_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ClaveProdServ', 'Clave Producto/Servicio'), ('ClaveUnidad', 'Clave Unidad'), ('UsoCFDI', 'Uso CFDI'), ('FormaPago', 'Forma de Pago'), ('MetodoPago', 'Método de Pago')], max_length=20)),
                ('clave', models.CharField(db_index=True, max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('palabras_clave', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catálogo SAT',
                'verbose_name_plural': 'Catálogos SAT',
                'unique_together': {('tipo', 'clave')},
            },
        ),
    ]
