# Generated by Django 5.1.7 on 2026-01-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_catalogosat'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='id_fiscalapi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Interno FiscalAPI'),
        ),
    ]
