# Generated by Django 5.2.8 on 2026-01-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_factura_id_fiscalapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo_relacion',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Tipo Relación'),
        ),
        migrations.AddField(
            model_name='factura',
            name='uuid_relacionado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UUID Relacionado'),
        ),
    ]
