# Generated by Django 5.2.8 on 2026-01-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_factura_tipo_relacion_factura_uuid_relacionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='tipo_comprobante',
            field=models.CharField(choices=[('I', 'I - Ingreso (Factura)'), ('E', 'E - Egreso (Nota de Crédito)')], default='I', max_length=1, verbose_name='Tipo de Comprobante'),
        ),
    ]
