# Generated by Django 5.2.8 on 2026-01-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_factura_tipo_comprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Matriz, Bodega Norte', max_length=50, verbose_name='Nombre de la Sucursal/Lugar')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección (Calle y Número)')),
                ('rfc_emisor', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC Emisor (Opcional)')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social (Opcional)')),
            ],
            options={
                'verbose_name': 'Lugar de Expedición',
                'verbose_name_plural': 'Lugares de Expedición',
            },
        ),
        migrations.CreateModel(
            name='SatImpuesto',
            fields=[
                ('clave', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='SatObjetoImpuesto',
            fields=[
                ('clave', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='SatRegimenFiscal',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='SatTipoComprobante',
            fields=[
                ('clave', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='SatUsoCFDI',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
    ]
