# Generated by Django 5.2.8 on 2026-01-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_lugar_satimpuesto_satobjetoimpuesto_satregimenfiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptofactura',
            name='objeto_impuesto',
            field=models.CharField(default='02', help_text='01: No objeto, 02: Sí objeto', max_length=5, verbose_name='Objeto Impuesto'),
        ),
    ]
