# Generated by Django 5.2.8 on 2026-01-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_conceptofactura_objeto_impuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriePersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, unique=True, verbose_name='Serie / Folio')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Serie Personalizada',
                'verbose_name_plural': 'Series Personalizadas',
            },
        ),
    ]
