# Generated by Django 5.2.8 on 2026-01-27 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_seriepersonalizada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('codigo_postal', models.CharField(db_index=True, max_length=10)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(default='MEX', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='facturacion.estado')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoPostalFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.municipio')),
            ],
        ),
    ]
