# Generated by Django 5.2.8 on 2026-01-27 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_colonia_estado_municipio_codigopostalfiscal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Interno / SKU')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Corto / Alias')),
                ('tipo', models.CharField(choices=[('P', 'Producto'), ('S', 'Servicio')], default='P', max_length=1, verbose_name='Tipo')),
                ('clave_prod_serv', models.CharField(default='01010101', help_text='Ej. 84111506', max_length=20, verbose_name='Clave Prod/Serv SAT')),
                ('clave_unidad', models.CharField(default='H87', help_text='Ej. E48, H87', max_length=10, verbose_name='Clave Unidad SAT')),
                ('descripcion_sat', models.TextField(help_text='Esta es la descripción que saldrá en el PDF/XML', verbose_name='Descripción para Factura')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('objeto_impuesto', models.CharField(choices=[('01', '01 - No objeto de impuesto'), ('02', '02 - Sí objeto de impuesto'), ('03', '03 - Sí objeto de impuesto y no obligado al desglose')], default='02', max_length=5, verbose_name='Objeto Impuesto')),
                ('permite_iva', models.BooleanField(default=True, verbose_name='Aplica IVA')),
                ('iva_tasa', models.DecimalField(decimal_places=4, default=0.16, max_digits=6, verbose_name='Tasa IVA (0.16, 0.08, 0.00)')),
                ('permite_ieps', models.BooleanField(default=False, verbose_name='Aplica IEPS')),
                ('ieps_tasa', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=6, null=True, verbose_name='Tasa IEPS')),
                ('permite_ret_iva', models.BooleanField(default=False, verbose_name='Retener IVA')),
                ('tasa_ret_iva', models.DecimalField(decimal_places=4, default=0.0, help_text='Ej. 0.0400 para Fletes, 0.1067 para Honorarios', max_digits=6, verbose_name='Tasa Ret. IVA')),
                ('permite_ret_isr', models.BooleanField(default=False, verbose_name='Retener ISR')),
                ('tasa_ret_isr', models.DecimalField(decimal_places=4, default=0.0, help_text='Ej. 0.0125 para RESICO, 0.1000 para Honorarios', max_digits=6, verbose_name='Tasa Ret. ISR')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_catalogo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto / Servicio',
                'verbose_name_plural': 'Catálogo Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
