# Generated by Django 5.2.8 on 2026-01-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_productoservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. IVA 16%, Retención ISR 1.25%', max_length=50)),
                ('impuesto', models.CharField(choices=[('IVA', 'IVA'), ('ISR', 'ISR'), ('IEPS', 'IEPS')], default='IVA', max_length=10)),
                ('tipo_factor', models.CharField(choices=[('Tasa', 'Tasa'), ('Cuota', 'Cuota'), ('Exento', 'Exento')], default='Tasa', max_length=10)),
                ('tasa_o_cuota', models.DecimalField(decimal_places=6, default=0.0, help_text='Para 16% poner 0.160000', max_digits=10)),
                ('categoria', models.CharField(choices=[('Traslado', 'Traslado (Cobrado)'), ('Retencion', 'Retención (Descontado)')], default='Traslado', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impuesto / Retención',
                'verbose_name_plural': 'Catálogo de Impuestos',
                'ordering': ['categoria', 'impuesto', 'tasa_o_cuota'],
            },
        ),
    ]
