# Generated by Django 5.2.8 on 2026-01-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_catalogoimpuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptofactura',
            name='retencion_impuesto_clave',
            field=models.CharField(default='002', max_length=3),
        ),
        migrations.AddField(
            model_name='conceptofactura',
            name='retencion_tasa',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='conceptofactura',
            name='traslado_impuesto_clave',
            field=models.CharField(default='002', max_length=3),
        ),
        migrations.AddField(
            model_name='conceptofactura',
            name='traslado_tasa',
            field=models.DecimalField(decimal_places=6, default=0.16, max_digits=8),
        ),
    ]
