# Generated by Django 5.2.8 on 2026-01-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_conceptofactura_retencion_impuesto_clave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Ext'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='numero_interior',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Int'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='pais',
            field=models.CharField(default='MEX', max_length=50, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='regimen_fiscal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Régimen Fiscal'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='uso_cfdi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uso CFDI'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Completa (Legado)'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='rfc_emisor',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC Emisor'),
        ),
    ]
