# Generated by Django 5.2.8 on 2026-01-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_lugar_calle_lugar_colonia_lugar_estado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lugar',
        ),
    ]
