# Generated by Django 5.1.7 on 2026-01-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_delete_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoservicio',
            name='impuesto_retencion',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'categoria': 'Retencion'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_retencion', to='facturacion.catalogoimpuesto', verbose_name='Impuesto Retención (Opcional)'),
        ),
        migrations.AddField(
            model_name='productoservicio',
            name='impuesto_traslado',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'categoria': 'Traslado'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_traslado', to='facturacion.catalogoimpuesto', verbose_name='Impuesto Traslado (IVA/IEPS)'),
        ),
    ]
