# Generated by Django 5.1.7 on 2026-01-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0019_productoservicio_impuesto_retencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfiscales',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Completa'),
        ),
    ]
