# Generated by Django 5.1.7 on 2025-12-15 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Cuenta')),
                ('moneda', models.CharField(choices=[('MXN', 'Pesos Mexicanos'), ('USD', 'Dólares Americanos')], default='MXN', max_length=3, verbose_name='Moneda')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Inicial')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='flujo_bancos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('retiro', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Retiros')),
                ('deposito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Depósitos')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('a_quien_se_pago', models.CharField(blank=True, max_length=200, null=True, verbose_name='A Quién se le Pagó')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA')),
                ('ret_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retención IVA')),
                ('ret_isr', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retención ISR')),
                ('ret_flete', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retención Flete')),
                ('intereses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Intereses')),
                ('comisiones', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Comisiones')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Adjuntar Comprobante (PDF/Imagen)')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flujo_bancos.categoria', verbose_name='Categoría')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='flujo_bancos.cuenta', verbose_name='Cuenta')),
                ('operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flujo_bancos.operacion', verbose_name='Operación')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flujo_bancos.subcategoria', verbose_name='Subcategoría')),
                ('unidad_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flujo_bancos.unidadnegocio', verbose_name='Unidad de Negocio')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
