# Generated by Django 5.1.7 on 2025-12-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo_bancos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='a_quien_se_pago',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='comisiones',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='deposito',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='intereses',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='ret_flete',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='retiro',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Abono (Ingreso)'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cargo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cargo (Egreso)'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='saldo_banco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Saldo'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tercero',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='A quién se pagó / De quién se recibió'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Adjuntar Comprobante'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='concepto',
            field=models.CharField(max_length=255, verbose_name='Concepto / Referencia'),
        ),
    ]
