# Generated by Django 5.1.7 on 2025-12-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo_bancos', '0002_remove_movimiento_a_quien_se_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre / Razón Social')),
                ('tipo', models.CharField(choices=[('ingreso', 'Cliente (Ingreso)'), ('egreso', 'Proveedor (Egreso)')], max_length=10, verbose_name='Tipo')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
            ],
        ),
    ]
