# Generated by Django 5.1.7 on 2025-12-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo_bancos', '0003_tercero'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='auditado',
            field=models.BooleanField(default=False, help_text='Indica si el movimiento ha sido revisado y no puede ser modificado ni eliminado.'),
        ),
    ]
