# Generated by Django 5.1.7 on 2025-12-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo_bancos', '0004_movimiento_auditado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15, verbose_name='Saldo Inicial'),
        ),
    ]
