# Generated by Django 5.1.7 on 2025-12-23 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo_bancos', '0005_alter_cuenta_saldo_inicial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente (Incompleto)'), ('TERMINADO', 'Terminado (Completo)')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Inicial'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='auditado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flujo_bancos.categoria'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='concepto',
            field=models.CharField(max_length=255, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flujo_bancos.operacion'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='ret_isr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='ret_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flujo_bancos.subcategoria'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tercero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='unidad_negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flujo_bancos.unidadnegocio'),
        ),
    ]
