# Generated by Django 5.1.7 on 2025-12-24 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo_bancos', '0006_alter_movimiento_options_movimiento_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flujo_bancos.operacion', verbose_name='Operación'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre Operación'),
        ),
    ]
