# Generated by Django 5.2.8 on 2026-01-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo_bancos', '0007_alter_movimiento_operacion_alter_operacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='iva_total_xml',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='IVA Extraído (XML)'),
        ),
        migrations.CreateModel(
            name='ComprobanteFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='xmls/%Y/%m/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/%Y/%m/')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='Folio Fiscal (UUID)')),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='flujo_bancos.movimiento')),
            ],
        ),
    ]
