# Generated by Django 5.2.8 on 2026-01-13 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo_bancos', '0008_movimiento_iva_total_xml_comprobantefiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='concepto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='flujo_bancos.cuenta', verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
