# Generated by Django 5.2.8 on 2026-01-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujo_bancos', '0009_alter_movimiento_concepto_alter_movimiento_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'permissions': [('acceso_flujo_bancos', 'Puede acceder al módulo de Bancos y Flujos')], 'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
    ]
