# Generated by Django 5.2.8 on 2026-01-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujo_bancos', '0010_alter_cuenta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha', 'id'], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
    ]
