# Generated by Django 5.2.8 on 2026-01-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo_bancos', '0011_alter_movimiento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantefiscal',
            name='monto_ret_isr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='comprobantefiscal',
            name='monto_ret_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
