# Generated by Django 5.2.8 on 2026-04-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujo_bancos', '0012_comprobantefiscal_monto_ret_isr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7, unique=True, verbose_name='Periodo YYYY-MM')),
                ('tc', models.DecimalField(decimal_places=4, default=17.0, max_digits=10, verbose_name='Tipo de Cambio USD→MXN')),
                ('ingresos_bancos_mxn', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ingresos_bancos_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ingresos_efectivo_mxn', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ingresos_efectivo_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gastos_bancos_mxn', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gastos_bancos_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gastos_efectivo_mxn', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gastos_efectivo_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('venta_emitida_mxn', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('venta_emitida_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('venta_operativa_mxn', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('venta_operativa_usd', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resumen Mensual',
                'verbose_name_plural': 'Resúmenes Mensuales',
                'ordering': ['-periodo'],
            },
        ),
    ]
