# Generated by Django 5.1.7 on 2025-11-06 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compras", "0011_remove_articulo_lleva_retencion_isr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_factura", models.CharField(max_length=50, unique=True)),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("pagada", models.BooleanField(default=False)),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Pago"),
                            ("PAGADA", "Pagada"),
                            ("VENCIDA", "Vencida"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orden_compra",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factura_cxp",
                        to="compras.ordencompra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField()),
                ("monto_pagado", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("TRANSFERENCIA", "Transferencia"),
                            ("CHEQUE", "Cheque"),
                            ("EFECTIVO", "Efectivo"),
                            ("TARJETA", "Tarjeta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=100)),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="cuentas_por_pagar.factura",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
