# Generated by Django 5.1.7 on 2025-11-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas_por_pagar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="alertas_enviadas",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="factura",
            name="dias_restantes_credito",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="factura",
            name="ultima_alerta_enviada",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="factura",
            name="estatus",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente de Pago"),
                    ("PAGADA", "Pagada"),
                    ("VENCIDA", "Vencida"),
                    ("POR_VENCER", "Por Vencer"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
    ]
