# Generated by Django 5.1.7 on 2025-11-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas_por_pagar", "0002_factura_alertas_enviadas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="archivo_factura",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="facturas_cxp/%Y/%m/",
                verbose_name="Archivo de Factura",
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="archivo_comprobante",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="comprobantes_pago/%Y/%m/",
                verbose_name="Comprobante de Pago",
            ),
        ),
    ]
