# Generated by Django 5.1.7 on 2025-11-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas_por_pagar", "0003_factura_archivo_factura_pago_archivo_comprobante"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pago",
            options={"ordering": ["factura", "numero_plazo"]},
        ),
        migrations.AddField(
            model_name="pago",
            name="fecha_plazo_programado",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha Programada del Plazo"
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="numero_plazo",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Número del plazo (1 para primer plazo, 2 para segundo, etc.)",
                verbose_name="Número de Plazo",
            ),
        ),
    ]
