# Generated by Django 5.1.7 on 2025-12-08 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_por_pagar', '0004_alter_pago_options_pago_fecha_plazo_programado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'permissions': [('acceso_cxp', 'Acceso al Módulo Cuentas por Pagar'), ('autorizar_pagos', 'Puede autorizar pagos'), ('ver_reportes_cxp', 'Puede ver reportes de CXP')]},
        ),
    ]
