# Generated by Django 5.1.7 on 2025-12-15 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_alter_ordencompra_options'),
        ('cuentas_por_pagar', '0005_alter_factura_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cantidad_plazos',
            field=models.PositiveIntegerField(default=1, help_text='1 para pago único, más de 1 para parcialidades', verbose_name='Cantidad de Pagos (Plazos)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_cxp', to='compras.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='orden_compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_cxp', to='compras.ordencompra'),
        ),
    ]
