# Generated by Django 5.1.7 on 2025-12-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_por_pagar', '0006_factura_cantidad_plazos_factura_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'permissions': [('acceso_cxp', 'Acceso al Módulo Cuentas por Pagar')]},
        ),
        migrations.AddField(
            model_name='factura',
            name='folio_cxp',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Folio Interno CXP'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(max_length=50, verbose_name='Folio Fiscal / Factura del Proveedor'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_plazo_programado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='numero_plazo',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Plazo'),
        ),
    ]
