# Generated by Django 5.1.7 on 2025-12-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_por_pagar', '0007_alter_factura_options_factura_folio_cxp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='folio_cxp',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True, verbose_name='Folio Interno CXP'),
            preserve_default=False,
        ),
    ]
