# Generated by Django 5.1.7 on 2025-12-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_por_pagar', '0009_alter_factura_folio_cxp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='folio_cxp',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Folio Interno CXP'),
        ),
    ]
