# Generated by Django 5.1.7 on 2025-12-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_por_pagar', '0010_alter_factura_folio_cxp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={},
        ),
    ]
