# Generated by Django 5.1.7 on 2025-12-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_por_pagar', '0011_alter_factura_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='folio_cxp',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Folio Interno CXP'),
        ),
    ]
