# Generated by Django 5.2.7 on 2026-07-11 17:59

import transferencias.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=transferencias.models._token, editable=False, max_length=64, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=140)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(db_index=True)),
                ('descargas', models.PositiveIntegerField(default=0)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(max_length=300, upload_to=transferencias.models._ruta_archivo)),
                ('nombre', models.CharField(max_length=255)),
                ('tamano', models.BigIntegerField(default=0)),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='transferencias.transferencia')),
            ],
        ),
    ]
