# Generated by Django 5.2.8 on 2026-07-19 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.CharField(blank=True, max_length=400)),
                ('data', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('publico', models.BooleanField(default=False)),
                ('miniatura', models.TextField(blank=True, help_text='data:image/png;base64,... opcional para preview en la lista.')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revision'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='BORRADOR', max_length=15)),
                ('enviado_aprobacion_en', models.DateTimeField(blank=True, null=True)),
                ('visto_por_aprobador_en', models.DateTimeField(blank=True, help_text='Primera vez que el aprobador designado abrio el diagrama en revision.', null=True)),
                ('decidido_en', models.DateTimeField(blank=True, null=True)),
                ('comentario_decision', models.CharField(blank=True, max_length=600)),
                ('modulo_vinculado', models.IntegerField(blank=True, default=None, null=True)),
                ('aprobador', models.ForeignKey(blank=True, help_text='Usuario designado para aprobar el diagrama actual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_a_aprobar', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_creados', to=settings.AUTH_USER_MODEL)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_decididos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='DiagramaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('ENVIO', 'Envio a aprobacion'), ('VISTO', 'Visto por el aprobador'), ('APROBAR', 'Aprobado'), ('RECHAZAR', 'Rechazado'), ('VINCULAR', 'Vinculado a modulo'), ('DESVINCULAR', 'Desvinculado de modulo')], max_length=15)),
                ('modulo', models.IntegerField(blank=True, default=None, null=True)),
                ('comentario', models.CharField(blank=True, max_length=600)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('aprobador_destinado', models.ForeignKey(blank=True, help_text='Cuando accion=ENVIO, a quien se le solicito aprobar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diagrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_aprobacion', to='diagramas.diagrama')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DiagramaCompartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(choices=[('ver', 'Solo ver'), ('editar', 'Puede editar')], default='ver', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('compartido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagramas_que_compartio', to=settings.AUTH_USER_MODEL)),
                ('diagrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidos', to='diagramas.diagrama')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagramas_compartidos_conmigo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Plantilla', max_length=160)),
                ('descripcion', models.CharField(blank=True, default='', max_length=400)),
                ('categoria', models.CharField(blank=True, default='Mis plantillas', max_length=80)),
                ('data', models.JSONField(default=dict)),
                ('miniatura', models.TextField(blank=True, default='', help_text='data:image/png;base64,... para preview en la galeria.')),
                ('ambito', models.CharField(choices=[('global', 'Global (predeterminada)'), ('personal', 'Personal')], db_index=True, default='personal', max_length=10)),
                ('orden', models.IntegerField(default=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_canvas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ambito', 'orden', '-actualizado'],
            },
        ),
        migrations.AddIndex(
            model_name='diagrama',
            index=models.Index(fields=['estado', 'modulo_vinculado'], name='diagramas_d_estado_424b91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diagramacompartido',
            unique_together={('diagrama', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='plantillacanvas',
            index=models.Index(fields=['ambito'], name='diagramas_p_ambito_c75801_idx'),
        ),
    ]
