# Generated by Django 5.1.7 on 2025-09-22 16:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import ternium.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la empresa', max_length=150, unique=True)),
                ('rfc', models.CharField(blank=True, help_text='Registro Federal de Contribuyentes', max_length=13, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, help_text='Dirección fiscal o principal', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico de contacto', max_length=254, null=True)),
                ('contacto_principal', models.CharField(blank=True, help_text='Nombre del contacto principal en la empresa', max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del operador', max_length=200, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o identificador del contenedor (Ej: CAJA-SECA-04)', max_length=100, unique=True)),
                ('placas', models.CharField(help_text='Placas o número de identificación del contenedor', max_length=20, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresas', models.ManyToManyField(related_name='contenedores', to='ternium.empresa', verbose_name='Unidades de Negocio (Empresas)')),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LineaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la línea de transporte', max_length=150, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresas', models.ManyToManyField(related_name='lineas_transporte', to='ternium.empresa', verbose_name='Unidades de Negocio (Empresas)')),
            ],
            options={
                'verbose_name': 'Línea de Transporte',
                'verbose_name_plural': 'Líneas de Transporte',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('ORIGEN', 'Origen'), ('DESTINO', 'Destino'), ('AMBOS', 'Ambos')], max_length=10)),
                ('es_patio', models.BooleanField(default=False, help_text='Marcar si este lugar funciona como un almacén temporal (patio).', verbose_name='¿Es un patio de inventario?')),
                ('empresas', models.ManyToManyField(blank=True, related_name='lugares', to='ternium.empresa', verbose_name='Empresas Asociadas')),
            ],
            options={
                'verbose_name': 'Lugar (Origen/Destino/Patio)',
                'verbose_name_plural': 'Lugares (Orígenes, Destinos y Patios)',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o descripción del material', max_length=150, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresas', models.ManyToManyField(related_name='materiales', to='ternium.empresa', verbose_name='Unidades de Negocio (Empresas)')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Cantidad Descargada (kg)')),
                ('fecha_descarga', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Descarga')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descargas_destino', to='ternium.lugar', verbose_name='Destino del Material')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descargas_origen', to='ternium.lugar', verbose_name='Origen del Material')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ternium.material', verbose_name='Material Descargado')),
            ],
            options={
                'verbose_name': 'Descarga de Material',
                'verbose_name_plural': 'Descargas de Materiales',
                'ordering': ['-fecha_descarga'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, help_text='Área o departamento del usuario', max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, help_text='Empresa a la que pertenece el usuario', max_length=100, null=True)),
                ('avatar', models.ImageField(default='avatars/default-avatar.png', upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TERMINADO', 'Terminado'), ('AUDITADO', 'Auditado')], default='PENDIENTE', max_length=10, verbose_name='Estatus')),
                ('remision', models.CharField(max_length=100, verbose_name='Remisión')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('inicia_ld', models.DateTimeField(blank=True, null=True, verbose_name='Inicia Carga')),
                ('termina_ld', models.DateTimeField(blank=True, null=True, verbose_name='Termina Carga')),
                ('folio_ld', models.CharField(blank=True, max_length=50, verbose_name='Folio Carga')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('inicia_dlv', models.DateTimeField(blank=True, null=True, verbose_name='Inicia Descarga')),
                ('termina_dlv', models.DateTimeField(blank=True, null=True, verbose_name='Termina Descarga')),
                ('folio_dlv', models.CharField(blank=True, max_length=50, verbose_name='Folio Descarga')),
                ('evidencia_carga', models.FileField(blank=True, null=True, upload_to='remisiones/cargas/')),
                ('evidencia_descarga', models.FileField(blank=True, null=True, upload_to='remisiones/descargas/')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario Adicional')),
                ('auditado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Auditoría')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('auditado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_auditadas', to=settings.AUTH_USER_MODEL, verbose_name='Auditado por')),
                ('contenedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.contenedor', verbose_name='Contenedor')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_destino', to='ternium.lugar', verbose_name='Lugar de Destino')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remisiones', to='ternium.empresa', verbose_name='Unidad de Negocio (Empresa)')),
                ('linea_transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.lineatransporte', verbose_name='Línea de Transporte')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.operador', verbose_name='Operador')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_origen', to='ternium.lugar', verbose_name='Lugar de Origen')),
            ],
            options={
                'verbose_name': 'Remisión',
                'verbose_name_plural': 'Remisiones',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_ld', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Peso Carga (Ton)')),
                ('peso_dlv', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Peso Descarga (Ton)')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente o destino específico para esta línea de material', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cliente', to='ternium.lugar', verbose_name='Cliente')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ternium.material', verbose_name='Material')),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ternium.remision')),
            ],
            options={
                'verbose_name': 'Detalle de Remisión',
                'verbose_name_plural': 'Detalles de Remisión',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(help_text='Ej: T-01, PL-04, VOLVO-23', max_length=100, unique=True, verbose_name='ID Interno (Nombre)')),
                ('license_plate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Placa o Matrícula')),
                ('make_model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marca y Modelo')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('vin', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Serie / VIN')),
                ('asset_type', models.CharField(choices=[('TRACTOR', 'Tracto'), ('PLANA', 'Plana'), ('MAQUINARIA', 'Maquinaria'), ('CARRO', 'Carro'), ('OTRO', 'Otro')], default='TRACTOR', max_length=20, verbose_name='Tipo de Activo')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('ownership', models.CharField(choices=[('PROPIA', 'Propia'), ('ARRENDADA', 'Arrendada')], default='PROPIA', max_length=20, verbose_name='Propiedad')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición')),
                ('operational_status', models.CharField(choices=[('ACTIVO', 'Activo'), ('FUERA_DE_SERVICIO', 'Fuera de Servicio'), ('EN_REPARACION', 'En Reparación')], default='ACTIVO', max_length=20, verbose_name='Estatus Operativo')),
                ('insurance_policy', models.CharField(blank=True, help_text='Compañía y número de póliza', max_length=255, null=True, verbose_name='Póliza de Seguro')),
                ('insurance_due_date', models.DateField(blank=True, null=True, verbose_name='Vencimiento de Póliza')),
                ('circulation_license', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tarjeta de Circulación')),
                ('license_due_date', models.DateField(blank=True, null=True, verbose_name='Vencimiento de Tarjeta')),
                ('display_photo', models.ImageField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_unidad_upload_path, verbose_name='Foto de Visualización')),
                ('unit_documents', models.FileField(blank=True, help_text='PDF con factura, pedimento u otros documentos importantes.', max_length=255, null=True, upload_to=ternium.models.get_unidad_upload_path, verbose_name='Documentos de la Unidad')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresas', models.ManyToManyField(related_name='unidades', to='ternium.empresa', verbose_name='Asignado a Empresa(s)')),
            ],
            options={
                'verbose_name': 'Activo (Unidad)',
                'verbose_name_plural': 'Activos (Unidades)',
                'ordering': ['internal_id'],
            },
        ),
        migrations.AddField(
            model_name='remision',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.unidad', verbose_name='Unidad'),
        ),
        migrations.CreateModel(
            name='RegistroLogistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remision', models.CharField(max_length=100, unique=True, verbose_name='Número de Remisión')),
                ('fecha_carga', models.DateField(verbose_name='Fecha de Carga')),
                ('boleta_bascula', models.CharField(max_length=100, verbose_name='# Boleta Báscula')),
                ('fecha_envio', models.DateField(blank=True, null=True, verbose_name='Fecha de Envío a Ternium')),
                ('toneladas_remisionadas', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Toneladas Remisionadas')),
                ('toneladas_recibidas', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Toneladas Recibidas Ternium')),
                ('pdf_registro_camion_remision', models.FileField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_registro_logistico_upload_path, verbose_name='1. PDF: Registro de Camión y Remisión')),
                ('pdf_remision_permiso', models.FileField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_registro_logistico_upload_path, verbose_name='2. PDF: Remisión y Permiso')),
                ('foto_superior_vacia', models.ImageField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_registro_logistico_upload_path, verbose_name='Foto Superior (Vacía)')),
                ('foto_frontal', models.ImageField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_registro_logistico_upload_path, verbose_name='Foto Frontal')),
                ('foto_superior_llena', models.ImageField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_registro_logistico_upload_path, verbose_name='Foto Superior (Llena)')),
                ('foto_trasera', models.ImageField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_registro_logistico_upload_path, verbose_name='Foto Trasera')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TERMINADO', 'Terminado'), ('AUDITADO', 'Auditado')], default='PENDIENTE', max_length=10, verbose_name='Estatus')),
                ('auditado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Auditoría')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('auditado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_logisticos_auditados', to=settings.AUTH_USER_MODEL, verbose_name='Auditado por')),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.operador', verbose_name='Nombre del Chofer')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.material', verbose_name='Material')),
                ('tolva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_como_tolva', to='ternium.contenedor', verbose_name='Tolva/Caja')),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.lineatransporte', verbose_name='Transportista')),
                ('tractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_como_tractor', to='ternium.unidad', verbose_name='Tractor')),
            ],
            options={
                'verbose_name': 'Registro Logístico',
                'verbose_name_plural': 'Registros Logísticos',
                'ordering': ['-fecha_carga', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EntradaMaquila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id_remito', models.CharField(help_text='Identificador único del remito de entrada', max_length=255, verbose_name='ID Remito')),
                ('num_boleta_remision', models.CharField(help_text='Número de boleta de remisión de báscula', max_length=255, verbose_name='Número de Boleta/Remisión')),
                ('fecha_ingreso', models.DateField(help_text='Fecha en que se registra la entrada', verbose_name='Fecha de Ingreso')),
                ('transporte', models.CharField(blank=True, help_text='Nombre de la empresa transportista', max_length=255, null=True, verbose_name='Línea de Transporte')),
                ('peso_remision', models.FloatField(help_text='Peso indicado en el remito', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Remisión (Ton)')),
                ('peso_bruto', models.FloatField(help_text='Peso total con carga', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Bruto (Ton)')),
                ('peso_tara', models.FloatField(help_text='Peso del vehículo vacío', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Tara (Ton)')),
                ('peso_neto', models.FloatField(editable=False, help_text='Peso calculado (Bruto - Tara)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Neto (Ton)')),
                ('calidad', models.CharField(help_text='Tipo y calidad del material recibido', max_length=100, verbose_name='Calidad del Material')),
                ('fecha_entrega_ternium', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega a Ternium')),
                ('foto_frontal', models.ImageField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_entrada_maquila_upload_path, verbose_name='1. Foto Frontal')),
                ('foto_superior_cargada', models.ImageField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_entrada_maquila_upload_path, verbose_name='2. Foto Superior (con Carga)')),
                ('foto_trasera', models.ImageField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_entrada_maquila_upload_path, verbose_name='3. Foto Trasera')),
                ('foto_superior_vacia', models.ImageField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_entrada_maquila_upload_path, verbose_name='4. Foto Superior (Vacía)')),
                ('documento_remision_clientes', models.FileField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_entrada_maquila_upload_path, verbose_name='5. Registro de Camiones y Remisión a Clientes')),
                ('diferencia_toneladas', models.FloatField(blank=True, editable=False, null=True, verbose_name='Diferencia (Ton)')),
                ('porcentaje_faltante', models.FloatField(blank=True, editable=False, null=True, verbose_name='% Diferencia')),
                ('alerta', models.BooleanField(default=False, editable=False, verbose_name='Alerta de Discrepancia')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TERMINADO', 'Terminado'), ('AUDITADO', 'Auditado')], default='PENDIENTE', max_length=10, verbose_name='Estatus')),
                ('auditado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('auditado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_auditadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Entrada de Maquila',
                'verbose_name_plural': 'Registros de Entradas de Maquila',
                'ordering': ['-fecha_ingreso', '-creado_en'],
                'indexes': [models.Index(fields=['c_id_remito'], name='ternium_ent_c_id_re_90643a_idx'), models.Index(fields=['fecha_ingreso'], name='ternium_ent_fecha_i_f10787_idx'), models.Index(fields=['status'], name='ternium_ent_status_dd571c_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventarioPatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('patio', models.ForeignKey(limit_choices_to={'es_patio': True}, on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='ternium.lugar')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='ternium.material')),
            ],
            options={
                'verbose_name': 'Inventario en Patio',
                'verbose_name_plural': 'Inventarios en Patios',
                'ordering': ['patio', 'material'],
                'unique_together': {('patio', 'material')},
            },
        ),
        migrations.AddIndex(
            model_name='remision',
            index=models.Index(fields=['status'], name='ternium_rem_status_8accb8_idx'),
        ),
        migrations.AddIndex(
            model_name='remision',
            index=models.Index(fields=['fecha'], name='ternium_rem_fecha_8bab77_idx'),
        ),
        migrations.AddIndex(
            model_name='registrologistico',
            index=models.Index(fields=['remision'], name='ternium_reg_remisio_f90e24_idx'),
        ),
        migrations.AddIndex(
            model_name='registrologistico',
            index=models.Index(fields=['status'], name='ternium_reg_status_c1abc1_idx'),
        ),
    ]
