# Generated by Django 5.1.7 on 2025-09-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0002_profile_telefono_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, default='General', help_text='Área o departamento del usuario', max_length=100, null=True),
        ),
    ]
