# Generated by Django 5.1.7 on 2025-09-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0003_alter_profile_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remision',
            name='operador',
        ),
        migrations.AlterField(
            model_name='remision',
            name='remision',
            field=models.CharField(max_length=100, unique=True, verbose_name='Remisión'),
        ),
    ]
