# Generated by Django 5.1.7 on 2025-09-23 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0004_remove_remision_operador_alter_remision_remision'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.operador', verbose_name='Operador'),
        ),
    ]
