# Generated by Django 5.1.7 on 2025-09-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0005_remision_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default-avatar.png', max_length=255, upload_to=''),
        ),
    ]
