# Generated by Django 5.1.7 on 2025-11-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='contacto_principal',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='rfc',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefono',
        ),
        migrations.AddField(
            model_name='empresa',
            name='prefijo',
            field=models.CharField(blank=True, help_text='Prefijo para folios (Ej. MTY). No incluyas el guión.', max_length=10, null=True, unique=True, verbose_name='Prefijo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(help_text='Nombre de la empresa. Ej: MONTERREY', max_length=150, unique=True, verbose_name='Nombre Completo'),
        ),
    ]
