# Generated by Django 5.1.7 on 2025-11-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0007_remove_empresa_contacto_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del origen (Ej: Nacional)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del origen.', null=True)),
            ],
            options={
                'verbose_name': 'Origen',
                'verbose_name_plural': 'Orígenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='origenes',
            field=models.ManyToManyField(blank=True, help_text='Seleccione uno o más orígenes asociados a esta empresa.', related_name='empresas', to='ternium.origen'),
        ),
    ]
