# Generated by Django 5.1.7 on 2025-12-06 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0008_origen_empresa_origenes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradamaquila',
            options={'ordering': ['-fecha_ingreso', '-creado_en'], 'permissions': [('can_audit_entrada', 'Puede auditar entradas de maquila')], 'verbose_name': 'Registro de Entrada de Maquila', 'verbose_name_plural': 'Registros de Entradas de Maquila'},
        ),
        migrations.AlterModelOptions(
            name='registrologistico',
            options={'ordering': ['-fecha_carga', '-creado_en'], 'permissions': [('can_audit_logistica', 'Puede auditar logística')], 'verbose_name': 'Registro Logístico', 'verbose_name_plural': 'Registros Logísticos'},
        ),
        migrations.AlterModelOptions(
            name='remision',
            options={'ordering': ['-fecha', '-creado_en'], 'permissions': [('can_audit_remision', 'Puede auditar remisiones'), ('view_ternium_module', 'Puede acceder al módulo Ternium')], 'verbose_name': 'Remisión', 'verbose_name_plural': 'Remisiones'},
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Cliente')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresas', models.ManyToManyField(blank=True, related_name='clientes_asociados', to='ternium.empresa', verbose_name='Unidades de Negocio (Empresas)')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='remision',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.cliente', verbose_name='Cliente Destino'),
        ),
    ]
