# Generated by Django 5.1.7 on 2025-12-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0009_alter_entradamaquila_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remision',
            options={'ordering': ['-fecha', '-creado_en'], 'permissions': [('can_audit_remision', 'Puede auditar remisiones'), ('view_ternium_module', 'Puede acceder al módulo Ternium'), ('use_ai_assistant', 'Puede usar el Asistente IA')], 'verbose_name': 'Remisión', 'verbose_name_plural': 'Remisiones'},
        ),
    ]
