# Generated by Django 5.1.7 on 2025-12-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0010_alter_remision_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remision',
            options={'ordering': ['-fecha', '-creado_en'], 'permissions': [('can_audit_remision', 'Puede auditar remisiones'), ('view_ternium_module', 'Puede acceder al módulo Ternium'), ('acceso_ia', 'Acceso a Inteligencia Artificial'), ('acceso_remisiones', 'Acceso a Módulo Remisiones'), ('acceso_dashboard_patio', 'Acceso a Dashboard Patios'), ('acceso_catalogos', 'Acceso a Catálogos'), ('acceso_reportes_kpi', 'Acceso a Reportes y KPIs')], 'verbose_name': 'Remisión', 'verbose_name_plural': 'Remisiones'},
        ),
    ]
