# Generated by Django 5.1.7 on 2025-12-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0011_alter_remision_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remision',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TERMINADO', 'Terminado'), ('AUDITADO', 'Auditado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10, verbose_name='Estatus'),
        ),
    ]
