# Generated by Django 5.1.7 on 2025-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0012_alter_remision_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Postal Fiscal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_fiscal',
            field=models.TextField(blank=True, help_text='Calle, Número, Colonia, Municipio, Estado (Opcional para timbrado, útil para PDF)', null=True, verbose_name='Dirección Fiscal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre fiscal tal cual aparece en la Constancia de Situación Fiscal (sin régimen capital, ej: SA de CV, si aplica).', max_length=255, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regimen_fiscal',
            field=models.CharField(blank=True, choices=[('601', '601 - General de Ley Personas Morales'), ('603', '603 - Personas Morales con Fines no Lucrativos'), ('605', '605 - Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', '606 - Arrendamiento'), ('612', '612 - Personas Físicas con Actividades Empresariales y Profesionales'), ('626', '626 - Régimen Simplificado de Confianza (RESICO)'), ('616', '616 - Sin obligaciones fiscales'), ('621', '621 - Incorporación Fiscal')], max_length=3, null=True, verbose_name='Régimen Fiscal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rfc',
            field=models.CharField(blank=True, help_text='Registro Federal de Contribuyentes', max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(help_text='Nombre corto o comercial. Ej: TERNIUM', max_length=150, unique=True, verbose_name='Nombre Comercial'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='prefijo',
            field=models.CharField(blank=True, help_text='Prefijo para folios (Ej. MTY).', max_length=10, null=True, unique=True, verbose_name='Prefijo'),
        ),
        migrations.AlterField(
            model_name='lineatransporte',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='lineas_transporte', to='ternium.empresa', verbose_name='Unidades de Negocio (Empresas)'),
        ),
    ]
