# Generated by Django 5.1.7 on 2025-12-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0013_empresa_codigo_postal_empresa_direccion_fiscal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='direccion_fiscal',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='regimen_fiscal',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='rfc',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(help_text='Nombre de la empresa. Ej: MONTERREY', max_length=150, unique=True, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='prefijo',
            field=models.CharField(blank=True, help_text='Prefijo para folios (Ej. MTY). No incluyas el guión.', max_length=10, null=True, unique=True, verbose_name='Prefijo'),
        ),
        migrations.AlterField(
            model_name='lineatransporte',
            name='empresas',
            field=models.ManyToManyField(related_name='lineas_transporte', to='ternium.empresa', verbose_name='Unidades de Negocio (Empresas)'),
        ),
    ]
