# Generated by Django 5.1.7 on 2025-12-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0014_remove_empresa_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugar',
            options={'ordering': ['nombre'], 'verbose_name': 'Lugar (Cliente/Origen)', 'verbose_name_plural': 'Lugares'},
        ),
        migrations.AddField(
            model_name='lugar',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='direccion_fiscal',
            field=models.TextField(blank=True, help_text='Calle, número, colonia, municipio, estado.', null=True, verbose_name='Dirección Fiscal'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre legal para facturación', max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='regimen_fiscal',
            field=models.CharField(blank=True, help_text='Ej: 601 - General de Ley Personas Morales', max_length=100, null=True, verbose_name='Régimen Fiscal'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='rfc',
            field=models.CharField(blank=True, help_text='Registro Federal de Contribuyentes', max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='uso_cfdi',
            field=models.CharField(blank=True, default='G03 - Gastos en general', max_length=100, null=True, verbose_name='Uso de CFDI'),
        ),
    ]
