# Generated by Django 5.1.7 on 2025-12-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0015_alter_lugar_options_lugar_codigo_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='direccion_fiscal',
        ),
        migrations.AddField(
            model_name='lugar',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad / Ciudad'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio / Alcaldía'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Exterior'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='numero_interior',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Interior'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='pais',
            field=models.CharField(blank=True, default='México', max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal (CP)'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='nombre',
            field=models.CharField(help_text='Nombre corto o alias operativo del lugar', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre legal tal cual aparece en la Constancia de Situación Fiscal', max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='regimen_fiscal',
            field=models.CharField(blank=True, choices=[('601', '601 - General de Ley Personas Morales'), ('603', '603 - Personas Morales con Fines no Lucrativos'), ('605', '605 - Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', '606 - Arrendamiento'), ('607', '607 - Régimen de Enajenación o Adquisición de Bienes'), ('608', '608 - Demás ingresos'), ('610', '610 - Residentes en el Extranjero sin Establecimiento Permanente en México'), ('611', '611 - Ingresos por Dividendos (socios y accionistas)'), ('612', '612 - Personas Físicas con Actividades Empresariales y Profesionales'), ('614', '614 - Ingresos por intereses'), ('615', '615 - Régimen de los ingresos por obtención de premios'), ('616', '616 - Sin obligaciones fiscales'), ('620', '620 - Sociedades Cooperativas de Producción que optan por diferir sus ingresos'), ('621', '621 - Incorporación Fiscal'), ('622', '622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'), ('623', '623 - Opcional para Grupos de Sociedades'), ('624', '624 - Coordinados'), ('625', '625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), ('626', '626 - Régimen Simplificado de Confianza')], max_length=5, null=True, verbose_name='Régimen Fiscal'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='rfc',
            field=models.CharField(blank=True, help_text='Registro Federal de Contribuyentes (Sin guiones)', max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='tipo',
            field=models.CharField(choices=[('ORIGEN', 'Origen'), ('DESTINO', 'Destino'), ('AMBOS', 'Ambos')], default='DESTINO', max_length=10),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='uso_cfdi',
            field=models.CharField(blank=True, choices=[('G01', 'G01 - Adquisición de mercancías'), ('G02', 'G02 - Devoluciones, descuentos o bonificaciones'), ('G03', 'G03 - Gastos en general'), ('I01', 'I01 - Construcciones'), ('I02', 'I02 - Mobiliario y equipo de oficina por inversiones'), ('I03', 'I03 - Equipo de transporte'), ('I04', 'I04 - Equipo de computo y accesorios'), ('I05', 'I05 - Dados, troqueles, moldes, matrices y herramental'), ('I06', 'I06 - Comunicaciones telefónicas'), ('I07', 'I07 - Comunicaciones satelitales'), ('I08', 'I08 - Otra maquinaria y equipo'), ('D01', 'D01 - Honorarios médicos, dentales y gastos hospitalarios'), ('D02', 'D02 - Gastos médicos por incapacidad o discapacidad'), ('D03', 'D03 - Gastos funerales'), ('D04', 'D04 - Donativos'), ('D05', 'D05 - Intereses reales efectivamente pagados por créditos hipotecarios'), ('D06', 'D06 - Aportaciones voluntarias al SAR'), ('D07', 'D07 - Primas por seguros de gastos médicos'), ('D08', 'D08 - Gastos de transportación escolar obligatoria'), ('D09', 'D09 - Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones'), ('D10', 'D10 - Pagos por servicios educativos (colegiaturas)'), ('S01', 'S01 - Sin efectos fiscales'), ('CP01', 'CP01 - Pagos'), ('CN01', 'CN01 - Nómina')], default='G03', max_length=5, null=True, verbose_name='Uso de CFDI'),
        ),
    ]
