# Generated by Django 5.1.7 on 2025-12-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0016_remove_lugar_direccion_fiscal_lugar_calle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='clave_sat',
            field=models.CharField(default='01010101', help_text='Clave de producto servicio del SAT', max_length=15),
        ),
        migrations.AddField(
            model_name='material',
            name='clave_unidad_sat',
            field=models.CharField(default='KGM', help_text='Clave de unidad SAT (ej. KGM, H87)', max_length=5),
        ),
    ]
