# Generated by Django 5.1.7 on 2025-12-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0017_material_clave_sat_material_clave_unidad_sat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='clave_sat',
            field=models.CharField(blank=True, help_text='Clave de producto servicio del SAT', max_length=15, null=True),
        ),
    ]
