# Generated by Django 5.1.7 on 2025-12-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0019_alter_lugar_regimen_fiscal_alter_lugar_uso_cfdi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='clave_unidad_sat',
            field=models.CharField(default='KGM', help_text='Clave de unidad SAT (ej. KGM, H87)', max_length=20),
        ),
    ]
