# Generated by Django 5.1.7 on 2025-12-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0020_alter_material_clave_unidad_sat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='empresa',
        ),
        migrations.AddField(
            model_name='profile',
            name='empresas_autorizadas',
            field=models.ManyToManyField(blank=True, help_text='Empresas con las que este usuario puede generar folios y ver información.', related_name='usuarios_autorizados', to='ternium.empresa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
