# Generated by Django 5.1.7 on 2025-12-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0021_remove_profile_empresa_profile_empresas_autorizadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='placas',
            field=models.CharField(help_text='Placas o número de identificación del contenedor', max_length=20),
        ),
    ]
