# Generated by Django 5.1.7 on 2025-12-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0023_alter_lugar_regimen_fiscal_alter_lugar_uso_cfdi'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='operadores', to='ternium.empresa', verbose_name='Unidades de Negocio (Empresas)'),
        ),
        migrations.AddField(
            model_name='operador',
            name='folio',
            field=models.CharField(blank=True, help_text='Número de licencia, gafete o ID interno', max_length=50, null=True, verbose_name='Folio / Licencia'),
        ),
    ]
