# Generated by Django 5.1.7 on 2025-12-15 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0024_operador_empresas_operador_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleremision',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ternium.material', verbose_name='Material'),
        ),
    ]
