# Generated by Django 5.1.7 on 2025-12-17 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0025_alter_detalleremision_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remision',
            name='evidencia_carga',
        ),
        migrations.RemoveField(
            model_name='remision',
            name='evidencia_descarga',
        ),
        migrations.CreateModel(
            name='EvidenciaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='remisiones/evidencias/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='ternium.remision')),
            ],
        ),
    ]
