# Generated by Django 5.1.7 on 2025-12-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0026_remove_remision_evidencia_carga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='evidencia_documento',
            field=models.FileField(blank=True, null=True, upload_to='remisiones/evidencias/', verbose_name='Evidencia (PDF o Foto)'),
        ),
        migrations.DeleteModel(
            name='EvidenciaRemision',
        ),
    ]
