# Generated by Django 5.2.8 on 2026-01-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0027_remision_evidencia_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='contenedor_manual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contenedor (Manual)'),
        ),
        migrations.AddField(
            model_name='remision',
            name='operador_manual',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Operador (Manual)'),
        ),
        migrations.AddField(
            model_name='remision',
            name='unidad_manual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad (Manual)'),
        ),
    ]
