# Generated by Django 5.2.8 on 2026-01-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0028_remision_contenedor_manual_remision_operador_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrologistico',
            name='chofer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Chofer'),
        ),
        migrations.AlterField(
            model_name='registrologistico',
            name='tolva',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tolva/Caja (Eco/Placas)'),
        ),
        migrations.AlterField(
            model_name='registrologistico',
            name='tractor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tractor (Eco/Placas)'),
        ),
    ]
