# Generated by Django 5.2.8 on 2026-01-15 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0029_alter_registrologistico_chofer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamaquila',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TERMINADO', 'Terminado'), ('AUDITADO', 'Auditado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='registrologistico',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TERMINADO', 'Terminado'), ('AUDITADO', 'Auditado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10, verbose_name='Estatus'),
        ),
        migrations.CreateModel(
            name='HistorialRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ternium.remision')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Remisión',
                'verbose_name_plural': 'Historial de Remisiones',
                'ordering': ['-fecha'],
            },
        ),
    ]
