# Generated by Django 5.2.8 on 2026-01-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0030_alter_entradamaquila_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialremision',
            name='accion',
        ),
        migrations.RemoveField(
            model_name='historialremision',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='historialremision',
            name='cambio',
            field=models.TextField(default=1, verbose_name='Descripción del cambio'),
            preserve_default=False,
        ),
    ]
