# Generated by Django 5.2.8 on 2026-01-15 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0031_remove_historialremision_accion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='remisiones/evidencias/', verbose_name='Archivo de Evidencia')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='ternium.remision')),
            ],
        ),
    ]
