# Generated by Django 5.2.8 on 2026-01-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0032_evidenciaremision'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='unidad_medida',
            field=models.CharField(choices=[('TON', 'Ton'), ('KG', 'Kg')], default='TON', max_length=3, verbose_name='Unidad'),
        ),
    ]
