# Generated by Django 5.2.8 on 2026-01-16 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0033_detalleremision_unidad_medida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plastico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remision', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remisión / Folio')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('folio_ld', models.CharField(blank=True, max_length=100, null=True, verbose_name='Folio LD')),
                ('folio_dlv', models.CharField(blank=True, max_length=100, null=True, verbose_name='Folio DLV')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción / Material')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Peso (Kg/Ton)')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Unitario')),
                ('venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Venta Total')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('AUDITADO', 'Auditado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plasticos_destino', to='ternium.lugar')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.operador')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plasticos_origen', to='ternium.lugar')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPlastico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambio', models.TextField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plastico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ternium.plastico')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaPlastico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='plastico/evidencias/', verbose_name='Archivo')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('plastico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='ternium.plastico')),
            ],
        ),
    ]
