# Generated by Django 5.2.8 on 2026-01-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0034_plastico_historialplastico_evidenciaplastico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plastico',
            name='unidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad / Placas'),
        ),
    ]
