# Generated by Django 5.2.8 on 2026-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0035_alter_plastico_unidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plastico',
            options={'permissions': [('can_audit_plastico', 'Puede auditar plásticos'), ('acceso_plastico', 'Puede acceder al módulo de plásticos')]},
        ),
        migrations.AddField(
            model_name='entradamaquila',
            name='comentario',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre la entrada', null=True, verbose_name='Comentarios Generales'),
        ),
    ]
