# Generated by Django 5.2.8 on 2026-01-16 14:35

import ternium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0036_alter_plastico_options_entradamaquila_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrologistico',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios Generales'),
        ),
        migrations.AddField(
            model_name='registrologistico',
            name='pdf_hoja_circulacion',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_registro_logistico_upload_path, verbose_name='3. PDF: Hoja de Circulación'),
        ),
    ]
