# Generated by Django 5.2.8 on 2026-01-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0037_registrologistico_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plastico',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='¿Pagado?'),
        ),
        migrations.AddField(
            model_name='plastico',
            name='pdf_adicional',
            field=models.FileField(blank=True, null=True, upload_to='plastico/adicionales/', verbose_name='PDF Adicional (Opcional)'),
        ),
    ]
