# Generated by Django 5.2.8 on 2026-01-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0038_plastico_pagado_plastico_pdf_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='empresa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Empresa Asignada'),
        ),
    ]
