# Generated by Django 5.2.8 on 2026-01-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0039_profile_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='plastico',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Peso Bruto'),
        ),
        migrations.AddField(
            model_name='plastico',
            name='peso_tarimas',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Peso Tarimas (Siempre KG)'),
        ),
        migrations.AddField(
            model_name='plastico',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'Kilogramos (KG)'), ('TON', 'Toneladas (TON)')], default='KG', max_length=3, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='plastico',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Peso Neto'),
        ),
    ]
