# Generated by Django 5.2.8 on 2026-01-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0040_plastico_peso_bruto_plastico_peso_tarimas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remision',
            options={'ordering': ['-fecha', '-creado_en'], 'permissions': [('can_audit_remision', 'Puede auditar remisiones'), ('view_ternium_module', 'Puede acceder al módulo Ternium'), ('acceso_ia', 'Acceso a Inteligencia Artificial'), ('acceso_remisiones', 'Acceso a Módulo Remisiones'), ('acceso_dashboard_patio', 'Acceso a Dashboard Patios'), ('acceso_catalogos', 'Acceso a Catálogos'), ('acceso_reportes_kpi', 'Acceso a Reportes y KPIs'), ('acceso_trane', 'Acceso al Portal Trane')], 'verbose_name': 'Remisión', 'verbose_name_plural': 'Remisiones'},
        ),
    ]
