# Generated by Django 5.2.8 on 2026-01-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0041_alter_remision_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradamaquila',
            name='c_id_remito',
            field=models.CharField(error_messages={'unique': 'Este ID de Remito ya está registrado en el sistema.'}, help_text='Identificador único del remito de entrada', max_length=255, unique=True, verbose_name='ID Remito'),
        ),
    ]
