# Generated by Django 5.2.8 on 2026-01-29 04:11

import ternium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0042_alter_entradamaquila_c_id_remito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrologistico',
            name='pdf_remision_permiso',
        ),
        migrations.AlterField(
            model_name='registrologistico',
            name='pdf_hoja_circulacion',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_registro_logistico_upload_path, verbose_name='2. PDF: Hoja de Circulación'),
        ),
    ]
