# Generated by Django 5.2.8 on 2026-01-29 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0043_remove_registrologistico_pdf_remision_permiso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTarima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tarima_chica_cant', models.IntegerField(default=0, verbose_name='Cant. Tarima Chica')),
                ('precio_chica', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Chica')),
                ('total_chica', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Chica')),
                ('tarima_grande_cant', models.IntegerField(default=0, verbose_name='Cant. Tarima Grande')),
                ('precio_grande', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Grande')),
                ('total_grande', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Grande')),
                ('gran_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gran Total')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='tarimas/evidencias/', verbose_name='Evidencia (PDF/Foto)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarimas_destino', to='ternium.lugar')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarimas_origen', to='ternium.lugar')),
            ],
            options={
                'verbose_name': 'Control de Tarima',
                'verbose_name_plural': 'Control de Tarimas',
                'ordering': ['-fecha'],
            },
        ),
    ]
