# Generated by Django 5.2.8 on 2026-02-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0044_controltarima'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrologistico',
            name='numero_permiso_sct',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Permiso SCT'),
        ),
    ]
