# Generated by Django 5.2.8 on 2026-02-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0045_registrologistico_numero_permiso_sct'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrologistico',
            name='placas_tolva',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Placas Tolva'),
        ),
        migrations.AddField(
            model_name='registrologistico',
            name='placas_tractor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Placas Tractor'),
        ),
    ]
