# Generated by Django 5.2.8 on 2026-02-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0046_registrologistico_placas_tolva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remision',
            name='remision',
            field=models.CharField(max_length=100, verbose_name='Remisión'),
        ),
        migrations.AlterUniqueTogether(
            name='remision',
            unique_together={('empresa', 'remision')},
        ),
    ]
