# Generated by Django 5.2.8 on 2026-02-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0047_alter_remision_remision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plastico',
            name='operador',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Operador'),
        ),
    ]
