# Generated by Django 5.2.8 on 2026-02-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0048_alter_plastico_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plastico',
            name='status',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('TERMINADO', 'Terminado'), ('AUDITADO', 'Auditado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20),
        ),
    ]
