# Generated by Django 5.2.8 on 2026-02-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0049_alter_plastico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleremision',
            name='peso_dlv',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Peso Descarga (Ton)'),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='peso_ld',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Peso Carga (Ton)'),
        ),
    ]
