# Generated by Django 5.2.8 on 2026-02-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0050_alter_detalleremision_peso_dlv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleremision',
            name='peso_dlv',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Peso Descarga (Kg)'),
        ),
        migrations.AlterField(
            model_name='detalleremision',
            name='peso_ld',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Peso Carga (Kg)'),
        ),
    ]
