# Generated by Django 5.2.8 on 2026-02-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0051_alter_detalleremision_peso_dlv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrologistico',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TERMINADO', 'Terminado'), ('AUDITADO', 'Auditado'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10, verbose_name='Estatus'),
        ),
    ]
