# Generated by Django 5.2.8 on 2026-02-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0052_alter_registrologistico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltarima',
            name='precio_mediana',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Mediana'),
        ),
        migrations.AddField(
            model_name='controltarima',
            name='tarima_mediana_cant',
            field=models.IntegerField(default=0, verbose_name='Cant. Tarima Mediana'),
        ),
        migrations.AddField(
            model_name='controltarima',
            name='total_mediana',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Mediana'),
        ),
    ]
