# Generated by Django 5.2.8 on 2026-02-06 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0053_controltarima_precio_mediana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plastico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ternium.empresa', verbose_name='Operación'),
        ),
    ]
