# Generated by Django 5.2.8 on 2026-02-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0054_plastico_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='manifiesto',
            field=models.FileField(blank=True, help_text='Documento oficial de manifiesto de carga/descarga', null=True, upload_to='remisiones/manifiestos/', verbose_name='Manifiesto (PDF o Foto)'),
        ),
    ]
