# Generated by Django 5.2.8 on 2026-02-25 01:36

import ternium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0055_remision_manifiesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrologistico',
            name='acuse_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_registro_logistico_upload_path, verbose_name='Acuse (PDF)'),
        ),
        migrations.AddField(
            model_name='registrologistico',
            name='fecha_correo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Correo'),
        ),
        migrations.AddField(
            model_name='registrologistico',
            name='pdf_factura',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_registro_logistico_upload_path, verbose_name='PDF Factura'),
        ),
        migrations.AddField(
            model_name='registrologistico',
            name='xml_factura',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=ternium.models.get_registro_logistico_upload_path, verbose_name='XML Factura'),
        ),
    ]
