# Generated by Django 5.2.8 on 2026-03-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0056_registrologistico_acuse_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='peso_rechazado',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Peso Rechazado (Kg)'),
        ),
    ]
