# Generated by Django 5.2.8 on 2026-03-10 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0057_detalleremision_peso_rechazado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='patio_rechazo',
            field=models.ForeignKey(blank=True, help_text='Si hay rechazo, indica a qué patio regresará el material.', limit_choices_to={'es_patio': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_rechazo', to='ternium.lugar', verbose_name='Patio de Rechazo'),
        ),
    ]
