# Generated by Django 5.2.8 on 2026-03-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0058_detalleremision_patio_rechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionManifiesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_manifiesto', to='ternium.material')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_manifiesto', to='ternium.lugar')),
            ],
            options={
                'verbose_name': 'Configuración de Manifiesto',
                'verbose_name_plural': 'Configuraciones de Manifiestos',
                'unique_together': {('origen', 'material')},
            },
        ),
    ]
