# Generated by Django 5.2.8 on 2026-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0059_configuracionmanifiesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='placas_contenedor_manual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Placas Contenedor (Manual)'),
        ),
        migrations.AddField(
            model_name='remision',
            name='placas_unidad_manual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Placas Unidad (Manual)'),
        ),
    ]
