# Generated by Django 5.2.8 on 2026-03-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0060_remision_placas_contenedor_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='trazabilidad_notas',
            field=models.TextField(blank=True, help_text='Apartado exclusivo para el seguimiento de materiales origen TRANE', null=True, verbose_name='Notas de Trazabilidad (TRANE)'),
        ),
    ]
