# Generated by Django 5.1.7 on 2026-03-17 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0061_remision_trazabilidad_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlManifiestoTrane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_captura', models.DateField(blank=True, null=True, verbose_name='Fecha de Captura')),
                ('operador_manual', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad_manual', models.CharField(blank=True, max_length=100, null=True)),
                ('placas_unidad_manual', models.CharField(blank=True, max_length=50, null=True)),
                ('contenedor_manual', models.CharField(blank=True, max_length=100, null=True)),
                ('placas_contenedor_manual', models.CharField(blank=True, max_length=50, null=True)),
                ('folio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Folio')),
                ('manifiesto', models.FileField(blank=True, null=True, upload_to='trane/manifiestos/', verbose_name='Manifiesto')),
                ('documento_trane', models.FileField(blank=True, null=True, upload_to='trane/documentos/', verbose_name='Documento Trane')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contenedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.contenedor')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_trane_destino', to='ternium.lugar')),
                ('linea_transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.lineatransporte')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.material')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.operador')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_trane_origen', to='ternium.lugar')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.unidad')),
            ],
            options={
                'verbose_name': 'Control Manifiesto Trane',
                'verbose_name_plural': 'Control Manifiestos Trane',
                'ordering': ['-fecha_captura', '-id'],
            },
        ),
    ]
