# Generated by Django 5.1.7 on 2026-03-17 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0062_controlmanifiestotrane'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlmanifiestotrane',
            name='remision_vinculada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ternium.remision', verbose_name='Operación Original'),
        ),
    ]
