# Generated by Django 5.1.7 on 2026-03-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0063_controlmanifiestotrane_remision_vinculada'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlmanifiestotrane',
            name='cantidad_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Cantidad (Kg)'),
        ),
    ]
