# Generated by Django 5.2.8 on 2026-03-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0064_controlmanifiestotrane_cantidad_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='foto_destruccion',
            field=models.ImageField(blank=True, null=True, upload_to='remisiones/destruccion/', verbose_name='3. Destrucción y Disposición'),
        ),
        migrations.AddField(
            model_name='remision',
            name='foto_ingreso',
            field=models.ImageField(blank=True, null=True, upload_to='remisiones/destruccion/', verbose_name='1. Ingreso de la unidad'),
        ),
        migrations.AddField(
            model_name='remision',
            name='foto_vertido',
            field=models.ImageField(blank=True, null=True, upload_to='remisiones/destruccion/', verbose_name='2. Vertido del material'),
        ),
    ]
