# Generated by Django 5.2.8 on 2026-03-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0065_remision_foto_destruccion_remision_foto_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remision',
            name='foto_destruccion',
        ),
        migrations.RemoveField(
            model_name='remision',
            name='foto_ingreso',
        ),
        migrations.RemoveField(
            model_name='remision',
            name='foto_vertido',
        ),
    ]
