# Generated by Django 5.2.8 on 2026-03-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0066_remove_remision_foto_destruccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='foto_ingreso',
            field=models.ImageField(blank=True, null=True, upload_to='remisiones_evidencias/', verbose_name='Foto de Ingreso'),
        ),
    ]
