# Generated by Django 5.2.8 on 2026-03-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0068_remision_foto_destruccion_remision_foto_vertido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='factura_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre/Folio Factura'),
        ),
        migrations.AddField(
            model_name='remision',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada'),
        ),
        migrations.AddField(
            model_name='remision',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
        migrations.AddField(
            model_name='remision',
            name='peso_bascula',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso Báscula'),
        ),
    ]
