# Generated by Django 5.2.8 on 2026-03-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0069_remision_factura_nombre_remision_hora_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='comentarios_destruccion',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios de Destrucción'),
        ),
        migrations.AddField(
            model_name='remision',
            name='fecha_destruccion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Destrucción'),
        ),
        migrations.AddField(
            model_name='remision',
            name='foto_destruccion_2',
            field=models.ImageField(blank=True, null=True, upload_to='remisiones/destruccion/', verbose_name='3.2 Destrucción y Disposición (Extra)'),
        ),
        migrations.AddField(
            model_name='remision',
            name='foto_ingreso_2',
            field=models.ImageField(blank=True, null=True, upload_to='remisiones/destruccion/', verbose_name='1.2 Ingreso de la unidad (Extra)'),
        ),
        migrations.AddField(
            model_name='remision',
            name='foto_vertido_2',
            field=models.ImageField(blank=True, null=True, upload_to='remisiones/destruccion/', verbose_name='2.2 Vertido del material (Extra)'),
        ),
    ]
