# Generated by Django 5.2.8 on 2026-03-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0070_remision_comentarios_destruccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='destruccion_material_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Material Destrucción 1'),
        ),
        migrations.AddField(
            model_name='remision',
            name='destruccion_material_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Material Destrucción 2'),
        ),
        migrations.AddField(
            model_name='remision',
            name='destruccion_peso_1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso Destrucción 1'),
        ),
        migrations.AddField(
            model_name='remision',
            name='destruccion_peso_2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso Destrucción 2'),
        ),
    ]
