# Generated by Django 5.2.8 on 2026-03-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0071_remision_destruccion_material_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='bultos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bultos'),
        ),
        migrations.AddField(
            model_name='remision',
            name='boleta_salida_medline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Boleta de Salida MEDLINE'),
        ),
    ]
