# Generated by Django 5.2.8 on 2026-03-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0072_detalleremision_bultos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioMedline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7, unique=True, verbose_name='Mes (YYYY-MM)')),
                ('precio', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='remision',
            name='boleta_salida_medline',
            field=models.FileField(blank=True, null=True, upload_to='remisiones/medline/', verbose_name='Boleta de Salida MEDLINE'),
        ),
    ]
