# Generated by Django 5.2.8 on 2026-03-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0073_preciomedline_alter_remision_boleta_salida_medline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preciomedline',
            old_name='precio',
            new_name='precio_archivo',
        ),
        migrations.AddField(
            model_name='preciomedline',
            name='precio_carton',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
