# Generated by Django 5.2.8 on 2026-04-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0074_rename_precio_preciomedline_precio_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='folio_medline',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio Medline'),
        ),
    ]
