# Generated by Django 5.2.8 on 2026-04-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0075_remision_folio_medline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.CharField(blank=True, choices=[('', 'Admin General'), ('flujos_bancos', 'Flujos Bancos'), ('ternium', 'Ternium')], default='', max_length=30, verbose_name='Rol de acceso'),
        ),
    ]
