# Generated by Django 5.2.8 on 2026-04-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0076_add_rol_to_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remision',
            options={'ordering': ['-fecha', '-creado_en'], 'permissions': [('can_audit_remision', 'Puede auditar remisiones'), ('view_ternium_module', 'Puede acceder al módulo Ternium'), ('acceso_ia', 'Acceso a Inteligencia Artificial'), ('acceso_remisiones', 'Acceso a Módulo Remisiones'), ('acceso_dashboard_patio', 'Acceso a Dashboard Patios'), ('acceso_catalogos', 'Acceso a Catálogos'), ('acceso_reportes_kpi', 'Acceso a Reportes y KPIs'), ('acceso_trane', 'Acceso al Portal Trane'), ('acceso_bancos', 'Acceso a Flujo Bancario'), ('acceso_dashboard', 'Acceso a Dashboard Principal'), ('acceso_diesel', 'Acceso a Control Diésel')], 'verbose_name': 'Remisión', 'verbose_name_plural': 'Remisiones'},
        ),
    ]
