# Generated by Django 5.2.8 on 2026-05-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0081_viajes_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarioparada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='id_ubicacion',
            field=models.CharField(blank=True, help_text='Generado automáticamente: ORnnnnnn para Origen, DEnnnnnn para Destino', max_length=15, null=True, unique=True, verbose_name='ID Ubicación'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='permiso_sct',
            field=models.CharField(blank=True, help_text='Ej: TPAF01', max_length=50, null=True, verbose_name='Permiso SCT (Tipo)'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='id_viaje',
            field=models.CharField(blank=True, help_text='Auto-generado tipo V-000001', max_length=20, unique=True, verbose_name='ID Viaje'),
        ),
        migrations.AlterField(
            model_name='viajemercancia',
            name='clave_producto',
            field=models.CharField(blank=True, help_text='Ej: 14121503', max_length=20, null=True, verbose_name='Clave SAT del Producto'),
        ),
        migrations.AlterField(
            model_name='viajemercancia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='viajemercancia',
            name='unidad_medida',
            field=models.CharField(default='H87', help_text='Código SAT: H87=Pieza, KGM=Kilogramo, TNE=Tonelada métrica', max_length=10, verbose_name='Unidad de medida'),
        ),
    ]
