# Generated by Django 5.2.8 on 2026-05-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0084_viaje_sueldo_liquidaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacionconcepto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liquidacionoperador',
            name='folio',
            field=models.CharField(blank=True, help_text='Auto-generado tipo L-000001', max_length=20, unique=True, verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='liquidacionoperador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
