# Generated by Django 5.2.8 on 2026-07-19 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0091_perm_acceso_utilidades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifiestoResiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_manifiesto', models.CharField(blank=True, default='', max_length=100, verbose_name='No. de manifiesto')),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manifiesto de Residuos',
                'verbose_name_plural': 'Manifiestos de Residuos',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='chatmensaje',
            new_name='ternium_cha_user_id_4d444f_idx',
            old_name='ternium_cha_user_id_creado__idx',
        ),
        migrations.AlterField(
            model_name='alerta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatmensaje',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='remisionalertamermalog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='manifiestoresiduos',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifiestos_residuos', to=settings.AUTH_USER_MODEL),
        ),
    ]
