# Generated by Django 5.2.8 on 2026-07-20 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0092_manifiestoresiduos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='remision',
            constraint=models.UniqueConstraint(condition=models.Q(('folio_medline__isnull', False), models.Q(('folio_medline', ''), _negated=True)), fields=('folio_medline',), name='uniq_folio_medline'),
        ),
    ]
