# Generated by Django 5.2.8 on 2026-07-20 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0092_manifiestoresiduos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # NEUTRALIZADA: la base de producción (Render) ya tenía folios_medline duplicados,
    # así que crear el índice único fallaba (IntegrityError: duplicate key). La unicidad
    # del folio Medline se valida a nivel de APLICACIÓN (RemisionForm.clean_folio_medline,
    # la API api_crear/editar_remision y el serializer DRF), no en la base de datos.
    # Se deja el archivo (sin operaciones) para no romper la dependencia de la 0094.
    operations = []
