# Generated by Django 5.2.8 on 2026-07-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0093_remision_uniq_folio_medline'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='no_exterior',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='No. Exterior'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='no_interior',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='No. Interior'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
