# Generated by Django 5.1.7 on 2026-08-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0094_cliente_calle_cliente_codigo_postal_cliente_colonia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='columnas_remisiones',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuración de la tabla de remisiones'),
        ),
    ]
