# Generated by Django 5.1.7 on 2026-08-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0095_profile_columnas_remisiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='activo',
            field=models.BooleanField(default=True, help_text='Los inactivos no aparecen al capturar remisiones, pero se conservan en el historial.', verbose_name='Activo'),
        ),
    ]
