# Generated by Django 5.2.7 on 2026-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ternium', '0096_operador_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleremision',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Precio por Kg'),
        ),
    ]
