# Generated by Django 5.1.7 on 2025-09-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='archivo_opcional',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_compra/opcionales/%Y/%m/', verbose_name='Archivo Opcional'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_compra/pagos/%Y/%m/', verbose_name='Comprobante de Pago'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='factura',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_compra/facturas/%Y/%m/', verbose_name='Factura (PDF/XML)'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='lista_para_auditoria',
            field=models.BooleanField(default=False, editable=False, help_text='Se marca automáticamente cuando se suben la factura y el comprobante de pago.'),
        ),
    ]
