# Generated by Django 5.1.7 on 2025-09-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_ordencompra_archivo_opcional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estatus',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('ENVIADA', 'Enviada'), ('RECIBIDA_PARCIAL', 'Recibida Parcialmente'), ('RECIBIDA_TOTAL', 'Recibida Totalmente'), ('EN_AUDITORIA', 'En Auditoría'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20),
        ),
    ]
