# Generated by Django 5.1.7 on 2025-09-23 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_ordencompra_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.unidadmedida'),
        ),
    ]
