# Generated by Django 5.1.7 on 2025-09-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_articulo_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesolicitud',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
