# Generated by Django 5.1.7 on 2025-09-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_detallesolicitud_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordencompra',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
