# Generated by Django 5.1.7 on 2025-09-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_detalleordencompra_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloproveedor',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
