# Generated by Django 5.1.7 on 2025-09-24 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_articuloproveedor_precio_unitario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='usuario_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Aprobador'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
    ]
