# Generated by Django 5.1.7 on 2025-09-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_ordencompra_usuario_aprobacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estatus',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('CANCELADA', 'Cancelada'), ('AUDITADA', 'Auditada')], default='BORRADOR', max_length=20),
        ),
    ]
