# Generated by Django 5.1.7 on 2025-09-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_ordencompra_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='moneda',
            field=models.CharField(choices=[('MXN', 'MXN - Pesos Mexicanos'), ('USD', 'USD - Dólares Americanos')], default='MXN', max_length=3),
        ),
    ]
