# Generated by Django 5.1.7 on 2025-09-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_alter_ordencompra_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='lleva_retencion_isr',
        ),
    ]
