# Generated by Django 5.1.7 on 2025-11-07 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_remove_articulo_lleva_retencion_isr'),
        ('ternium', '0008_origen_empresa_origenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='origen',
            field=models.ForeignKey(blank=True, help_text='Origen del artículo (filtrado por empresa)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='ternium.origen'),
        ),
    ]
