# Generated by Django 5.1.7 on 2025-11-07 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_articulo_origen'),
        ('ternium', '0008_origen_empresa_origenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='origen',
            field=models.ForeignKey(blank=True, help_text='Origen del artículo (filtrado por empresa y tipo)', limit_choices_to={'tipo': 'ORIGEN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='ternium.lugar'),
        ),
    ]
