# Generated by Django 5.1.7 on 2025-11-07 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_alter_articulo_origen'),
        ('ternium', '0008_origen_empresa_origenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='lugar',
            field=models.ForeignKey(blank=True, help_text='Empresa (Lugar de Origen) asociada al proveedor', limit_choices_to={'tipo': 'ORIGEN'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='ternium.lugar'),
        ),
    ]
