# Generated by Django 5.1.7 on 2025-11-07 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_proveedor_lugar'),
        ('ternium', '0008_origen_empresa_origenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcompra',
            name='lugar',
            field=models.ForeignKey(default=1, help_text='Empresa (Lugar de Origen) de la solicitud', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='ternium.lugar', verbose_name='Empresa (Lugar de Origen)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ternium.empresa', verbose_name='Operación'),
        ),
    ]
