# Generated by Django 5.1.7 on 2025-11-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0015_solicitudcompra_lugar_alter_solicitudcompra_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordencompra",
            name="cantidad_plazos",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Solo aplica si la modalidad es 'A plazos'",
                null=True,
                verbose_name="Cantidad de Plazos",
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="modalidad_pago",
            field=models.CharField(
                choices=[
                    ("UNA_EXHIBICION", "A una sola exhibición"),
                    ("A_PLAZOS", "A plazos"),
                ],
                default="UNA_EXHIBICION",
                max_length=20,
                verbose_name="Modalidad de Pago",
            ),
        ),
    ]
