# Generated by Django 5.1.7 on 2025-11-08 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0016_ordencompra_cantidad_plazos_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ordencompra",
            name="comprobante_pago_subido",
            field=models.BooleanField(
                default=False, verbose_name="Comprobante de pago subido"
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="comprobante_subido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comprobantes_subidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="factura_subida",
            field=models.BooleanField(default=False, verbose_name="Factura subida"),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="factura_subida_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas_subidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="fecha_comprobante_subido",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="fecha_factura_subida",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordencompra",
            name="lista_para_auditar",
            field=models.BooleanField(default=False, verbose_name="Lista para auditar"),
        ),
        migrations.AlterField(
            model_name="ordencompra",
            name="estatus",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("APROBADA", "Aprobada"),
                    ("LISTA_PARA_AUDITAR", "Lista para Auditar"),
                    ("CANCELADA", "Cancelada"),
                    ("AUDITADA", "Auditada"),
                ],
                default="BORRADOR",
                max_length=20,
            ),
        ),
    ]
