# Generated by Django 5.1.7 on 2025-12-08 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0017_ordencompra_comprobante_pago_subido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'permissions': [('acceso_compras', 'Acceso al Módulo de Compras'), ('aprobar_solicitudes', 'Puede aprobar solicitudes de compra'), ('ver_reportes_compras', 'Puede ver reportes de compras')]},
        ),
    ]
