# Generated by Django 5.1.7 on 2025-12-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_alter_ordencompra_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='lleva_iva',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='lleva_retencion_iva',
        ),
        migrations.AddField(
            model_name='articulo',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ej: 16.00', max_digits=5, verbose_name='% IVA'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='porcentaje_retencion_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ej: 4.00', max_digits=5, verbose_name='% Retención IVA'),
        ),
    ]
