# Generated by Django 5.2.8 on 2026-01-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0019_remove_articulo_lleva_iva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='lista_para_auditar',
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('AUDITADA', 'Auditada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='lista_para_auditoria',
            field=models.BooleanField(default=False, editable=False, help_text='Indicador interno: True si tiene ambos documentos.'),
        ),
    ]
