# Generated by Django 5.2.8 on 2026-07-19 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacionViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('es_plantilla', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict)),
                ('resultado', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulaciones_viaje', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulación de viaje',
                'verbose_name_plural': 'Simulaciones de viaje',
                'ordering': ['-actualizado'],
            },
        ),
    ]
